
title = "From Species to Languages: a phylogenetic approach to human prehistory"

doi = ""

abstract = """ Linguistic evidence plays an important role in our understanding of Mayan prehistory.
How ever, traditional linguistic methods have a number of limitations. Language family trees based
on the "comparative method" yield a relative chronology of lineage divergence events, but cannot
quantify uncertainty or provide absolute divergence dates. An alternative method, glottochronology,
attempts to provide absolute dates but these estimates are generally thought to be unreliable, due
largely to the assumption of a universal and constant rate of lexical replacement. The paucity of
alternative historical sources has meant that , despite these problems, theories of Mayan origin and
diversity have utilized glottochronology-based divergence time estimates. Here, we apply stochastic
models of language evolution and computational phylogenetic methods to Mayan lexical data to infer
the relationships within the Mayan language family and to estimate confidence intervals for lineage
divergence times without the assumption of rate constancy. Our analyses highlight a number of areas
of uncertainty in Mayan language relation ships. Divergence time estimates also showed uncertainty
but suggest the family may be older than previously thought. We evaluate how these results relate to
existing archaeological and linguistic evidence for the origin and diversification of the Mayan
language family. We conclude with suggestions for future research including ways to improve the
precision of date estimates.

"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Quentin D. Atkinson"
]

# parts of the world
groups = ["Mayan"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@atkinson2006"

# type of study
type = ["phylogenetic", "dating", "trait"]
framework = ['network', 'bayesian']

# short label of taxa "37 languages from.."
description = "30 Mayan languages"

## Methods:
# | Model                                | Score    | Program         | Comment            |
# |--------------------------------------|----------|-----------------|--------------------|
# | restriction site model               |          | MrBayes (3.1.1) |                    |
# | dating                               |          | r8s 1.7         |                    |
# | Stochastic Dollo                     |          | Traitlab        |                    |
# | Phylogeography ASR                   |          | MacClade        |                    |
# | Consensus Network                    |          | SplitsTree      |                    |
# |                                      |          |                 |                    |



## Analysis:

# Both analyses were run for 1.3 million generations sampling every 1,000 trees. A
# 'burn-in' period of 300,000 trees for each run was used to avoid sampling trees
# before the run had reached convergence.

# data
[data]
    [data.lexicon]
    ntaxa = 44
    nchars = "100"
    nsites = "~1200"
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh100'
    comment = ''


[calibration]
    notes = ""

    [calibration.classicalmaya]
    taxa = ["yuca1254"]
    age = "uniform(300, 700)"
    units = "ad"
    description = "Earliest dated monument, Stela 29 at Tikal, 292A.D., although most stela are later. Items identified by Boot (2002) as being younger than 700A.D. were excluded"

    [calibration.colonialyucatec]
    taxa = ["yuca1254"]
    age = "uniform(1570, 1590)"
    units = "ad"
    description = "Source document written around 1580."

    [calibration.colonialkaqchikel]
    taxa = ["kaqc1270"]
    age = "uniform(1630, 1647)"
    units = "ad"
    description = "Sources compiled in the years before publication."

    [calibration.sipsak]
    taxa = ["sipa1247", "saca1238"]
    age = ">1551"
    units = "ad"
    description = "Titulo of Sacapulas (1551) recognizes the two languages as being distinct"

    [calibration.poq]
    taxa = ["poco1241"]
    age = "uniform(1250, 1450)"
    units = "ad"
    description = "Ethno-historical evidence of Rabinal Quiche invasion \"driving a wedge\" between what is now Poqomam and Poqomchi."
   
    [calibration.kt]
    taxa = ["cakc1244"]
    age = ">1493"
    units = "ad"
    description = "Ethno-history indicates the populations had evidently been separated before this time."

# analysis information
[analysis]
    [analysis.mrbayes]
    tool = 'mrbayes'
    model = 'restriction site'
    details = ""

    [analysis.r8s]
    tool = 'r8s'
    model = ''
    details = ""

    [analysis.traitlab]
    tool = 'traitlab'
    model = 'stochastic dollo'
    details = ""

    [analysis.macclade]
    tool = 'macclade'
    model = 'asr'
    details = "parsimony ASR of geographical location"

    [analysis.neighbornet]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""

    [analysis.consensusnetwork]
    tool = 'splitstree'
    model = 'consensus network'
    details = ""


[inferredages]
    
    notes = ""
    
    [inferredage.root]
    taxa = ['maya1287']
    age = "hpd(3900, 9100)"
    units = "y2000"
    details = "best fitting model"
    best = "true"

[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/atkinson2006" }
links = []
