title = "Rates of change and phylogenetic signal in Mixtec tone"

doi = "10.1163/22105832-bja10031"

abstract = """
Despite the abundance of tonal languages around the world, the diachrony of tone is still poorly
understood, especially when compared to segmental sound change. This lacuna has contributed to the untested
assumption that tones are inherently unstable and change unpredictably. This paper addresses the questions of
whether tones change faster than segments and whether tones show less phylogenetic signal than segments in the
Mixtec languages of southern Mexico. To this end, I created a database of tonal and segmental sound changes across a
sample of 42 Mixtec languages. I calculated phylogenetic signal with the metric D and estimated rates of change with
a hidden Markov model across a posterior sample of phylogenetic trees. The results show that the majority of tone
changes show phylogenetic signal and that they generally do not change at a faster rate than segments.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ['Sandra Auderset']

# parts of the world
groups = ['Mixtecan']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Auderset_2024"

# type of study
type = ['trait']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['likelihood'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.tones]
    ntaxa = 42
    nchars = 263
    nsites = 263
    datatype = 'correspondences'
    source = '@Auderset_2023'
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.Auderset_2024]
    source = '@Auderset_2024'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.d]
    tool = 'caper'
    model = 'd'
    details = ""
    data = ""
    times = "263"

    [analysis.rate]
    tool = 'corHMM'
    model = 'ard'
    details = ""
    data = ""
    times = "263"



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = ["https://osf.io/9sfmq/"]