title = "An experimental study comparing linguistic phylogenetic reconstruction methods"

doi = "10.1075/dia.30.2.01bar"

abstract = """
This paper reports a simulation study comparing and evaluating the performance of different linguistic phylogeny reconstruction methods on model datasets for which the true trees are known. UPGMA performed least well, then (in ascending order) neighbor joining, the method of Gray & Atkinson and finally maximum parsimony. Weighting characters greatly improves the accuracy of maximum parsimony and maximum compatibility if the characters with high weights exhibit low homoplasy.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["François Barbançon", "Steven N. Evans", "Luay Nakhleh", "Donald A. Ringe", "Tandy Warnow"]

# parts of the world
groups = ['global']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Barban_on_2013"

# type of study
type = ['methodological']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['distance', 'parsimony', 'likelihood', 'bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = "Flawed simulation study to evaluate the effectiveness of phylogenetic methods."

# data
[data]

    notes = ""
    
    [data.simulated]
    ntaxa = 30
    nchars = 360
    nsites = 260
    datatype = 'simulated data'
    source = ''
    items = ''
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.simulation_basic_experiment_upgma]
        tool = 'paup*'
        model = 'upgma'
        details = ""
        data = ""
        

    [analysis.simulation_basic_experiment_maximum_parsimony]
        tool = 'paup*'
        model = 'maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_basic_experiment_neighbor_joining]
        tool = 'paup*'
        model = 'neighbor joining'
        details = ""
        data = ""
        

    [analysis.simulation_basic_experiment_weighted_maximum_parsimony]
        tool = 'paup*'
        model = 'weighted maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_basic_experiment_weighted_maximum_compatibility]
        tool = 'paup*'
        model = 'weighted maximum compatibility'
        details = ""
        data = ""
        

    [analysis.simulation_basic_experiment_bayesian]
        tool = 'mrbayes'
        model = 'bayesian'
        details = ""
        data = ""
        

    [analysis.simulation_experiment2_upgma]
        tool = 'paup*'
        model = 'upgma'
        details = ""
        data = ""
        

    [analysis.simulation_experiment2_maximum_parsimony]
        tool = 'paup*'
        model = 'maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_experiment2_neighbor_joining]
        tool = 'paup*'
        model = 'neighbor joining'
        details = ""
        data = ""
        

    [analysis.simulation_experiment2_weighted_maximum_parsimony]
        tool = 'paup*'
        model = 'weighted maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_experiment2_weighted_maximum_compatibility]
        tool = 'paup*'
        model = 'weighted maximum compatibility'
        details = ""
        data = ""
        

    [analysis.simulation_experiment2_bayesian]
        tool = 'mrbayes'
        model = 'bayesian'
        details = ""
        data = ""
        

    [analysis.simulation_experiment3_upgma]
        tool = 'paup*'
        model = 'upgma'
        details = ""
        data = ""
        

    [analysis.simulation_experiment3_maximum_parsimony]
        tool = 'paup*'
        model = 'maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_experiment3_neighbor_joining]
        tool = 'paup*'
        model = 'neighbor joining'
        details = ""
        data = ""
        

    [analysis.simulation_experiment3_weighted_maximum_parsimony]
        tool = 'paup*'
        model = 'weighted maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_experiment3_weighted_maximum_compatibility]
        tool = 'paup*'
        model = 'weighted maximum compatibility'
        details = ""
        data = ""
        

    [analysis.simulation_experiment3_bayesian]
        tool = 'mrbayes'
        model = 'bayesian'
        details = ""
        data = ""
        

    [analysis.simulation_experiment4_upgma]
        tool = 'paup*'
        model = 'upgma'
        details = ""
        data = ""
        

    [analysis.simulation_experiment4_maximum_parsimony]
        tool = 'paup*'
        model = 'maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_experiment4_neighbor_joining]
        tool = 'paup*'
        model = 'neighbor joining'
        details = ""
        data = ""
        

    [analysis.simulation_experiment4_weighted_maximum_parsimony]
        tool = 'paup*'
        model = 'weighted maximum parsimony'
        details = ""
        data = ""
        

    [analysis.simulation_experiment4_weighted_maximum_compatibility]
        tool = 'paup*'
        model = 'weighted maximum compatibility'
        details = ""
        data = ""
        

    [analysis.simulation_experiment4_bayesian]
        tool = 'mrbayes'
        model = 'bayesian'
        details = ""
        data = ""
        

