title = "Evolution of initiation rites during the Austronesian dispersal"

doi = "10.1177/00368504211031364"

abstract = """
As adaptive systems, kinship and its accompanying rules have co-evolved with elements of complex societies, including wealth inheritance, subsistence, and power relations. Here we consider an aspect of kinship evolution in the Austronesian dispersal that began from about 5500 BP in Taiwan, reaching Melanesia about 3200 BP, and dispersing into Micronesia by 1500 BP. Previous, foundational work has used phylogenetic comparative methods and ethnolinguistic information to infer matrilocal residence in proto-Austronesian societies. Here we apply Bayesian phylogenetic analyses to a data set on Austronesian societies that combines existing data on marital residence systems with a new set of ethnographic data, introduced here, on initiation rites. Transition likelihoods between cultural-trait combinations were modeled on an ensemble of 1000 possible Austronesian language trees, using Reversible Jump Markov Chain Monte Carlo (RJ-MCMC) simulations. Compared against a baseline phylogenetic model of independent evolution, a phylogenetic model of correlated evolution between female and male initiation rites is substantially more likely (log Bayes factor: 17.9). This indicates, over the generations of Austronesian dispersal, initiation rites were culturally stable when both female and male rites were in the same state (both present or both absent), yet relatively unstable for female-only rites. The results indicate correlated phylogeographic evolution of cultural initiation rites in the prehistoric dispersal of Austronesian societies across the Pacific. Once acquired, male initiation rites were more resilient than female-only rites among Austronesian societies.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["R Alexander Bentley", "William R Moritz", "Damian J Ruck", "Michael J O’Brien"]

# parts of the world
groups = ['Austronesian']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Bentley_2021"

# type of study
type = ['asr', 'trait']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['likelihood', 'bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.dplace]
    ntaxa = 79
    nchars = 2
    nsites = 2
    datatype = 'ethnographic features'
    source = '@DPLACE'
    items = ''
    comment = ''
    
# published phylogenies
[phylogenies]
    [phylogenies.austronesian]
    source = '@Gray2009'
    comment = ''



# analysis information
[analysis]
    
    notes = ""
    
    [analysis.bayestraits_dep]
    tool = 'bayestraits'
    model = 'dependent+rjmcmc'
    details = ""
    data = ""
    
    [analysis.bayestraits_indep]
    tool = 'bayestraits'
    model = 'independent+rjmcmc'
    details = ""
    data = ""



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []