
title = "A combined comparative and phylogenetic analysis of the Chapacuran language family"

doi = "10.1086/687383"

abstract = """The Chapacuran language family, with three extant members and nine historically attested lects, has yet to be classified following modern standards in historical linguistics. This paper presents an internal classification of these languages by combining both the traditional comparative method (CM) and Bayesian phylogenetic inference (BPI). We identify multiple systematic sound correspondences and 285 cognate sets of basic vocabulary using the available documentation. These allow us to reconstruct a large portion of the Proto-Chapacuran phonemic inventory and identify tentative major subgroupings. The cognate sets form the input for the BPI analysis, which uses a stochastic Continuous-Time Markov Chain to model the change of these cognate sets over time. We test various models of lexical substitution and evolutionary clocks, and use ethnohistorical information and data collection dates to calibrate the resulting trees. The CM and BPI analyses produce largely congruent results, suggesting a division of the family into three different clades."""


# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Joshua Birchall",
    "Michael Dunn",
    "Simon J. Greenhill"
]

# parts of the world
groups = ["Chapacuran"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Birchall_et_al2016"

# type of study
type = ["phylogenetic", "dating", "network", "delta", "qresidual"]

# short label of taxa "37 languages from.."
taxa = "10 Chapacuran languages"

# data
[data]
    [data.lexicon]
    ntaxa = 10
    nchars = 207
    nsites = 285
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh200'
    comment = ''

[calibration]
    [calibration.tapekura]
    taxa = ["chap1269"]
    # corrected for 2010 starting 180 - (2010 - 1950)
    calibration = "120"
    units = "ybp" # ybp
    description = "Although the primary source of data on Tapakura and Kitemoka was only published in the early twentieth century in Créqui-Montfort and Rivet (1913), the data were originally collected during d’Orbigny’s trip through lowland Bolivia, which took place between 1826 and 1833."

    [calibration.kitemoka]
    taxa = ["kite1237"]
    # corrected for 2010 starting 180 - (2010 - 1950)
    calibration = "120"
    units = "ybp" # ybp
    description = "Although the primary source of data on Tapakura and Kitemoka was only published in the early twentieth century in Créqui-Montfort and Rivet (1913), the data were originally collected during d’Orbigny’s trip through lowland Bolivia, which took place between 1826 and 1833"

    [calibration.tapekura_and_kitemoka]
    taxa = ["kite1238"]
    # corrected for 2010 starting 236 - (2010 - 1950)
    calibration = "lognormal(250, 0.6, 176, realspace=True)"
    units = "ybp" # ybp
    description = "The Tapakura people were first contacted in the 1580s during an expedition led by Lorenzo Suarez de Figueroa (Meireles 1989:66). By 1630, the Tapakuras were already in close contact with Jesuit missionaries and portions of the population were considered yanacona, a regional term meaning serf or servant of the Spaniards (Maurtua 1909 [cited in Métraux 1948]). However, the first clear mention of the Kitemoka people is not until the settlement of the mission Concepción de Chiquitos in 1707 (d’Orbigny 1839a:596). Calibration: This calibration was implemented as a log-normal distribution with a mean of 250 years (in real space), a standard deviation of 0.6, and an offset of 236 years."

    [calibration.tora]
    taxa = ["tora1263"]
    # corrected for 2010 starting 90 - (2010 - 1950)
    calibration = "30"
    units = "ybp" # ybp
    description = "The data available for both Torá and Urupá were collected in 1922 by the anthropologist Curt Nimuendajú. The Urupá data were collected at Colônia Rodolfo Miranda and the Torá data were collected along settlements on the lower Marmelos River (Nimuendajú 1925)."

    [calibration.urupa]
    taxa = ["urup1245"]
    # corrected for 2010 starting 90 - (2010 - 1950)
    calibration = "30"
    units = "ybp" # ybp
    description = "The data available for both Torá and Urupá were collected in 1922 by the anthropologist Curt Nimuendajú. The Urupá data were collected at Colônia Rodolfo Miranda and the Torá data were collected along settlements on the lower Marmelos River (Nimuendajú 1925). Calibration: 90 years ago."

    [calibration.toradivergence]
    taxa = ["tora1263"]
    # corrected for 2010 starting 170 - (2010 - 1950)
    calibration = "lognormal(300, 0.4, 110, realspace=True)+originate"
    units = "ybp" # ybp
    description = "The earliest known mention of the Torá comes from a letter written by Jesuit priest Bartolomeu Rodrigues in 1714 during his travels along the lower Madeira River (Menéndez 1981). In 1716, the Torá were attacked by an expedition led by the captain general of Pará, João de Barros Guerra, in reprisal for their raids on the villages and transport ships along the lower Madeira and middle Amazonas rivers (Nimuendajú 1925). Calibration: This calibration was implemented on the stem of the lineage leading to the Torá tip. The probability distribution was modeled using a log-normal distribution with a mean of 300 years (in real space), a standard deviation of 0.4, and an offset of 170 years. This distribution had 95% of its values between 296 years and 777 years, with a median of 447 years."

    [calibration.yarutip]
    taxa = ["yaru1257"]
    # corrected for 2010 starting 80 - (2010 - 1950)
    calibration = "20"
    units = "ybp" # ybp
    description = "The only data available on the Jarú language were collected in 1927 at the Colônia Rodolfo Miranda by members of the Comissão Rondon (Rondon and de Faria 1948). Calibration: 80 years ago."

    [calibration.morecojubim]
    taxa = ["yaru1257"]
    # corrected for 2010 starting 179 - (2010 - 1950)
    calibration = "lognormal(201, 0.6, 119, realspace=True)"
    units = "ybp" # ybp
    description = "The Moré and the Cojubim speak similar languages but are geographically separated by the lower Guaporé River. The Moré were first contacted in the 1740s as Jesuit missions spread into the Bolivian lower Guaporé basin. No known mention is made of the Cojubim (Cautarios) as a distinct ethnic group in the historical record until an expedition led by Portuguese military engineer Ricardo Franco de Almeida Serra in 1781 (Almeida Serra 1857:422). Calibration: This calibration was implemented as a log-normal probability distribution with a mean of 201 years (in real space), a standard deviation of 0.6, and an offset of 179 years. This gave a probability distribution where 95% of the values were between 231 years and 723 years, with a median of 347 years."


# analysis information
[analysis]
    [analysis.tree1]
    tool = 'beast'
    model = 'ctmc+strict'
    details = ""

    [analysis.tree2]
    tool = 'beast'
    model = 'ctmc+relaxed'
    details = "best fitting model"

    [analysis.tree3]
    tool = 'beast'
    model = 'stochastic dollo+strict'
    details = ""

    [analysis.tree4]
    tool = 'beast'
    model = 'stochastic dollo+relaxed'
    details = ""

    [analysis.neighbornet]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""

    [analysis.delta]
    tool = 'splitstree'
    model = 'delta'
    details = ""

    [analysis.qresidual]
    tool = 'splitstree'
    model = 'qresidual'
    details = ""



[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/birchall_et_al2016" }
lexibank = { title = "Lexibank Dataset", link = "https://github.com/lexibank/birchallchapacuran" }
links = []
