
title = "Computational phylogenetics and the internal structure of Pama-Nyungan"

doi = "10.1353/lan.2012.0081"

abstract = """
We present the first proposal of detailed internal subgrouping and higher-order structure of the Pama-Nyungan family of Australian languages. Previous work has identified more than twentyfive primary subgroups in the family, with little indication of how these groups might fit together. Some work has assumed that reconstruction of higher nodes in the tree was impossible, either because extensive internal borrowing has obscured more remote relations, or because the languages are not sufficiently well attested (see, for example, Bowern & Koch 2004b, Dixon 1997). With regard to the first objection, work by Alpher and Nash (1999) and Bowern and colleagues (2011) shows that loan levels are not high enough to obscure vertical transmission for all but a few languages. New data remove the second objection. Here we use Bayesian phylogenetic inference to show that the Pama-Nyungan tree has a discernible internal subgrouping. We identify four major divisions within the family and discuss the implications of this grouping for future work on the family.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Claire Bowern",
    "Quentin D. Atkinson"
]

# parts of the world
groups = ["Pama-Nyungan"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Bowern2012"

# type of study
type = ["phylogenetic",]  # phylogenetic,phylogeography,macroevolutionary,trait

# short label of taxa "37 languages from.."
description = "194 Pama-Nyungan languages"

# data
[data]
    [data.lexicon]
    ntaxa = 194
    nchars = 189
    nsites = 14613
    datatype = 'lexical cognates'
    source = '@chirila'
    items = 'swadesh200'
    comment = ''
    

# analysis information
[analysis]
    [analysis.tree1]
    tool = 'beast'
    model = 'ctmc+strict'
    details = ""

    [analysis.tree2]
    tool = 'beast'
    model = 'covarion+strict'
    details = ""

    [analysis.tree3]
    tool = 'beast'
    model = 'stochasticdollo+strict'
    details = ""

    [analysis.tree4]
    tool = 'beast'
    model = 'stochasticdollo+relaxed'
    details = "best fitting model"

    [analysis.tree5]
    tool = 'beast'
    model = 'covarion+relaxed'
    details = ""

    [analysis.tree6]
    tool = 'beast'
    model = 'ctmc+relaxed'
    details = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/bowern_and_atkinson2012" }
lexibank = { }
links = []
