title = "Rate variation in language change: Toward distributional phylogenetic modeling"

doi = "10.51315/9783935751384.008"

abstract = """
Since the advent of phylogenetic linguistics, researchers have used a large
number of phylogenetic comparative methods adapted from computational bio-
logy to model and analyze the dynamics of change of a wide range of linguistic
features. Models of this sort vary in complexity; the simplest models of change
assume homogeneity of transition rates within families, while state-of-the-art
models of heterotachy allow transition rates to vary across lineages within a
family. In this contribution, I review a range of applications of biological models of
rate variation to questions in diachronic linguistics and highlight some models
from computational biology that have remained largely overlooked by linguists.
Building off of these and other biological models, I sketch out a program for what
I term DISTRIBUTIONAL PHYLOGENETIC MODELING, inspired by an analogous
recently proposed family of hierarchical Bayesian models. I report the results of
some work in progress carried out within this framework and present a case
study illustrating the flexibility of the approach.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Chundra A. Cathcart"]

# parts of the world
groups = ['Indo-European', 'global']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Cathcart_2024"

# type of study
type = ['trait', 'methodological']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""

    [data.romance_phylogeny1]
    ntaxa = 67
    nchars = "?"
    nsites = "?"
    datatype = 'lexical cognates (autodetected)'
    source = '@Jaeger2018'
    items = ''
    comment = ''

    [data.romance_phylogeny2]
    ntaxa = 67
    nchars = "?"
    nsites = "?"
    datatype = 'phonetic traits'
    source = '@SoundComparisons'
    items = ''
    comment = ''

    [data.romance_morphology]
    ntaxa = 67
    nchars = 66
    nsites = 171
    datatype = 'structural features'
    source = '@Beniamine_2022'
    items = ''
    comment = 'verbal morphology'

    [data.wals]
    ntaxa = 698
    nchars = "?"
    nsites = "?"
    datatype = 'structural features'
    source = '@WALS'
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.romance_phylogeny]
    tool = 'revbayes'
    model = 'custom'
    details = ""
    data = "@data.romance_phylogeny1;@data.romance_phylogeny2"

    [analysis.romance_verbal_morphology]
    tool = 'stan'
    model = 'custom'
    details = ""
    data = "@data.romance_morphology;@analysis.romance_phylogeny"


    [analysis.phylogeography]
    tool = 'stan'
    model = 'custom'
    details = ""
    data = "@data.wals"

    [analysis.phylogeography_FAM]
    tool = 'stan'
    model = 'custom'
    details = "allows change rates and stationary probabilities for features to vary across families."
    data = "@data.wals"

    [analysis.phylogeography_FAM_GEO]
    tool = 'stan'
    model = 'custom'
    details = "allows change rates and stationary probabilities for features to vary across families."
    data = "@data.wals"

[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []