
title = "Formal Syntax and Deep History"

doi = "10.3389/fpsyg.2020.488871"

abstract = """
We show that, contrary to long-standing assumptions, syntactic traits, modeled here within the generative biolinguistic framework, provide insights into deep-time language history. To support this claim, we have encoded the diversity of nominal structures using 94 universally definable binary parameters, set in 69 languages spanning across up to 13 traditionally irreducible Eurasian families. We found a phylogenetic signal that distinguishes all such families and matches the family-internal tree topologies that are safely established through classical etymological methods and datasets. We have retrieved "near-perfect" phylogenies, which are essentially immune to homoplastic disruption and only moderately influenced by horizontal convergence, two factors that instead severely affect more externalized linguistic features, like sound inventories. This result allows us to draw some preliminary inferences about plausible/implausible cross-family classifications; it also provides a new source of evidence for testing the representation of diversity in syntactic theories.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Andrea Ceolin",
    "Cristina Guardiano",
    "Monica Alexandrina Irimia",
    "Giuseppe Longobardi"
]

# parts of the world
groups = ["Indo-European", "Others"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Ceolin_2020"

# type of study
type = ['phylogenetic', 'delta', 'qresidual']
framework = ['network', 'bayesian', 'distance']

# short label of taxa "37 languages from.."
description = "69 Indo-European & other languages"

# data
[data]
    [data.parameters]
    ntaxa = 69
    nchars = 94
    nsites = 94
    datatype = 'structural features'
    source = ''
    items = ''
    comment = ''
    

# analysis information
[analysis]
    [analysis.upgma]
    tool = 'phylip'
    model = 'upgma'
    details = ""

    [analysis.neighbornet]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""

    [analysis.delta]
    tool = 'splitstree'
    model = 'delta'
    details = ""

    [analysis.qresidual]
    tool = 'splitstree'
    model = 'qresidual'
    details = ""

    [analysis.beast1]
    tool = 'beast2'
    model = 'ctmc+relaxed(log)+yule'
    details = "best-fitting model"
    best = 'true'

    [analysis.beast2]
    tool = 'beast2'
    model = 'ctmc+relaxed(exp)+yule'
    details = ""

    [analysis.beast3]
    tool = 'beast2'
    model = 'ctmc+strict'
    details = ""

    [analysis.beast4]
    tool = 'beast2'
    model = 'stochasticdollo+relaxed(log)+yule'
    details = ""

    [analysis.beast5]
    tool = 'beast2'
    model = 'ctmc+randomclock+yule'
    details = ""

    [analysis.beast6]
    tool = 'beast2'
    model = 'ctmc+relaxedclock(log)+coalescent(const)'
    details = ""

    [analysis.beast7]
    tool = 'beast2'
    model = 'ctmc+relaxedclock(log)+coalescent(exp)'
    details = ""
    
    [analysis.beast8]
    tool = 'beast2'
    model = 'ctmc+relaxedclock(log)+coalescent(bayes)'
    details = ""
    
    [analysis.beast9]
    tool = 'beast2'
    model = 'ctmc+relaxedclock(log)+coalescent(extbayes)'
    details = ""
    
    
[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/ceolin_et_al2020" }
lexibank = {}
links = []

