title = "Cross-cultural patterns of marriage and inheritance: A phylogenetic approach"

doi = "10.1016/0162-3095(95)00127-1"

abstract = """
There is a strong correlation between marriage system and wealth inheritance pattern across societies (Hartung
1982); as the degree of polygyny increases, so too does the degree of male bias in inheritance. In this paper, we
reevaluate this pattern using a new technique in cross-cultural analyses that effectively controls for the
nonindependence of cultures (Galton's problem) through the identification of independent instances of cultural
change (Mace and Pagel 1994). First, we produce cultural phylogenetic trees for the societies under study, from
phylogenies previously constructed on the basis of linguistic similarity (Ruhlen 1987). Then, following standard
methods for the analysis of discrete characters on phylogenetic trees, we use parsimony to determine the ancestral
condition of both marriage and inheritance, and subsequently tally the number of independent instances of cultural
change in each trait. The results show that transitions to polygyny are much more commonly associated with
male-biased inheritance than are transitions to monogamy across human societies in our sample. They illustrate how
the degree of change in the evolution of these traits differs considerably between divergent cultural groups. The
advantages of this technique are discussed.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Guy Cowlishaw", "Ruth Mace"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Cowlishaw_1996"

# type of study
type = ['trait']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['parsimony'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.ethnographicatlas]
    ntaxa = 411
    nchars = 3
    nsites = 3
    datatype = 'ethnographic features'
    source = '@EthAtlas'
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.AfroAsiatic]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"

    [phylogenies.Austric]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"

    [phylogenies.DeneCaucasian]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"

    [phylogenies.Eurasiatic]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"

    [phylogenies.IndoPacific]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"

    [phylogenies.NigerKordofanian]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"

    [phylogenies.NiloSaharan]
    source = ''
    comment = "manually constructed from Ruhlen 1987, 1991"



# analysis information
[analysis]
    
    notes = ""
    
    [analysis.AfroAsiatic]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""
    
    [analysis.Austric]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""

    [analysis.DeneCaucasian]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""

    [analysis.Eurasiatic]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""

    [analysis.IndoPacific]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""

    [analysis.NigerKordofanian]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""

    [analysis.NiloSaharan]
    tool = 'MacClade'
    model = 'maximum parsimony'
    details = ""
    data = ""





[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []