title = "Linguistic Phylogenetic Inference by PAM-like Matrices"

doi = "10.1080/09296174.2012.659001"

abstract = """
We apply to the task of linguistic phylogenetic inference a successful cognate
identification learning model based on point accepted mutation (PAM)-like matrices.
We train our system and we employ the learned parameters for measuring the lexical
distance between languages. We estimate phylogenetic trees using distance-based
methods on an Indo-European database. Our results reproduce correctly all the
established major language groups and subgroups present in the dataset, are
compatible with the Indo-European benchmark tree and include also some of the
supported higher-level structures. We review and compare other studies reported in
the literature with regard to recognized aspects of the Indo-European language family.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Antonella Delmestri", "Nello Cristianini"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Delmestri_2012"

# type of study
type = ['phylogenetic', 'methodological']
framework = ['distance']
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.Dyen1992]
    ntaxa = 84
    nchars = 200
    nsites = "?" 
    datatype = 'lexical cognates'
    source = '@Dyen1992'
    items = 'swadesh200'
    comment = ''


# analysis information
[analysis]
    
    notes = "n.b. main aim is alignment of lexical items and cognate detection rather than phylogeny"
    
    [analysis.nj_d1]
    tool = 'unknown'
    model = 'neighbor-joining'
    details = ""
    data = "3 variants of distance data {d1, d2, d3}"

    [analysis.nj_d2]
    tool = 'unknown'
    model = 'neighbor-joining'
    details = ""
    data = "3 variants of distance data {d1, d2, d3}"

    [analysis.nj_d3]
    tool = 'unknown'
    model = 'neighbor-joining'
    details = ""
    data = "3 variants of distance data {d1, d2, d3}"

    [analysis.upgma_d1]
    tool = 'unknown'
    model = 'UPGMA'
    details = ""
    data = "3 variants of distance data {d1, d2, d3}"

    [analysis.upgma_d2]
    tool = 'unknown'
    model = 'UPGMA'
    details = ""
    data = "3 variants of distance data {d1, d2, d3}"

    [analysis.upgma_d3]
    tool = 'unknown'
    model = 'UPGMA'
    details = ""
    data = "3 variants of distance data {d1, d2, d3}"


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []