title = "Evolved structure of language shows lineage-specific trends in word-order universals"

doi = "10.1038/nature09923"

abstract = """
Languages vary widely but not without limit. The central goal of linguistics is to describe the diversity of human languages and explain the constraints on that diversity. Generative linguists following Chomsky have claimed that linguistic diversity must be constrained by innate parameters that are set as a child learns a language1,2. In contrast, other linguists following Greenberg have claimed that there are statistical tendencies for co-occurrence of traits reflecting universal systems biases3,4,5, rather than absolute constraints or parametric variation. Here we use computational phylogenetic methods to address the nature of constraints on linguistic diversity in an evolutionary framework6. First, contrary to the generative account of parameter setting, we show that the evolution of only a few word-order features of languages are strongly correlated. Second, contrary to the Greenbergian generalizations, we show that most observed functional dependencies between traits are lineage-specific rather than universal tendencies. These findings support the view that—at least with respect to word order—cultural evolution is the primary factor that determines linguistic structure, with the current state of a linguistic system shaping and constraining future states.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Michael Dunn",
    "Simon J. Greenhill",
    "Stephen C. Levinson",
    "Russell D. Gray"
    
]

# parts of the world
groups = ['Austronesian', 'Bantu', 'Indo-European', 'Uto-Aztecan']

# bibkey citation in sources.bib
bibkey = "@Dunn2011"

# type of study
type = ['macroevolutionary']

# short label of taxa "37 languages from.."
description = "79 Indo-European languages, 130 Austronesian languages, 66 Bantu languages and 26 Uto-Aztecan languages"

# data
[data]
    [data.utoaztecan]
    ntaxa = 26
    nchars = 108
    nsites = "?"
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh100'
    comment = ''

[data.structural]
    ntaxa = 26
    nchars = 8
    nsites = 8
    datatype = 'structural features'
    source = '@WALS'
    items = ''
    comment = ''

[phylogenies]
    [phylogenies.bantu]
    source = '@Holden2005'
    comment = ''

    [phylogenies.indoeuropean]
    source = '@Dyen1992'
    comment = ''

    [phylogenies.austronesian]
    source = '@ABVD'
    comment = ''

# analysis information
[analysis]
# Posterior tree distributions for all four lexical datasets were estimated
# using a Bayesian Markov Chain Monte Carlo approach implemented in the program
# BayesPhylogenies (Pagel and Meade 2004, 2005). This Bayesian approach samples
# from the posterior probability distribution the trees that explain the data
# well under a given model of evolution. Following Gray et al (2009), we used a
# two-state covarion model of lexical evolution. The covarion model allows
# cognate sets to change between different rates at different points along the
# tree. We ran the Bantu, Indo-European, and Utoaztecan data for five million
# generations as plots of the critical parameters (log likelihood, tree length)
# showed that this was sufficient for convergence. To avoid auto-correlation we
# sampled trees from the posterior every 5,000 generations. Burn-in was set to
# two million generations after inspection of the log-likelihood plots and these
# initial trees were discarded leaving a total of 600 trees in the posterior
# sample. Due to the much larger size of the Austronesian data this analysis was
# run for much longer – 100 million generations over six replicates – to
# ensure adequate mixing (Gray et al. 2009). Trees were sampled every 100,000
# generations and burn-in was set to 40 million generations after inspection of
# critical parameters showed that convergence had been reached. This left a
# total of 4,200 trees in the posterior tree sample.
    [analysis.utoaztecan]
    tool = 'bayestraits'
    model = 'two-state time reversible, gamma'
    details = "5 million"
    data = "@data.utoaztecan"

    [analysis.bayestraits_indep]
    tool = 'bayestraits'
    model = 'discrete+independent'
    details = ""

    [analysis.bayestraits_dep]
    tool = 'bayestraits'
    model = 'discrete+dependent'
    details = ""

[links]
links = []