title = "Evolved structure of language shows lineage-specific trends in word-order universals"

doi = "10.1038/nature09923"

# short description of the study.
description = """
Modelling the constraints on word order universals
"""

# Description of the findings
results = """
Contrary to the generative account of parameter setting, we show
that the evolution of only a few word-order features of languages are strongly
correlated. Second, contrary to the Greenbergian generalizations, we show that
most observed functional dependencies between traits are lineage-specific rather
than universal tendencies. These findings support the view that—at least with
respect to word order—cultural evolution is the primary factor that determines
linguistic structure, with the current state of a linguistic system shaping and
constraining future states.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Michael Dunn",
    "Simon J. Greenhill",
    "Stephen C. Levinson",
    "Russell D. Gray"
    
]

# parts of the world
groups = ['Austronesian', 'Bantu', 'Indo-European', 'Uto-Aztecan']

# bibkey citation in sources.bib
bibkey = "@Dunn2011"

# type of study
type = ['macroevolutionary']

# short label of taxa "37 languages from.."
taxa = "79 Indo-European languages, 130 Austronesian languages, 66 Bantu languages and 26 Uto-Aztecan languages"

# data
[data]
    [data.bantu]
    ntaxa = 66
    nchars = 92
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Holden2005'

    [data.indoeuropean]
    ntaxa = 82 
    nchars = 200
    nsites = 4049
    datatype = 'lexical cognates'
    source = '@Dyen1992'

    [data.austronesian]
    ntaxa = 130
    nchars = 210
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Greenhill2008'

    [data.utoaztecan]
    ntaxa = 26
    nchars = 108
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Holden2002'

    [data.structural]
    ntaxa = 26
    nchars = 8
    nsites = 8
    datatype = 'structural features'
    source = '@WALS'
    

# analysis information
[analysis]
# Posterior tree distributions for all four lexical datasets were estimated
# using a Bayesian Markov Chain Monte Carlo approach implemented in the program
# BayesPhylogenies (Pagel and Meade 2004, 2005). This Bayesian approach samples
# from the posterior probability distribution the trees that explain the data
# well under a given model of evolution. Following Gray et al (2009), we used a
# two-state covarion model of lexical evolution. The covarion model allows
# cognate sets to change between different rates at different points along the
# tree. We ran the Bantu, Indo-European, and Utoaztecan data for five million
# generations as plots of the critical parameters (log likelihood, tree length)
# showed that this was sufficient for convergence. To avoid auto-correlation we
# sampled trees from the posterior every 5,000 generations. Burn-in was set to
# two million generations after inspection of the log-likelihood plots and these
# initial trees were discarded leaving a total of 600 trees in the posterior
# sample. Due to the much larger size of the Austronesian data this analysis was
# run for much longer – 100 million generations over six replicates – to
# ensure adequate mixing (Gray et al. 2009). Trees were sampled every 100,000
# generations and burn-in was set to 40 million generations after inspection of
# critical parameters showed that convergence had been reached. This left a
# total of 4,200 trees in the posterior tree sample.
    [analysis.bayesphylogenies]
    tool = 'bayestraits'
    model = 'two-state time reversible, gamma'
    details = "5 million"

    [analysis.bayestraits]
    tool = 'bayestraits'
    details = "dependent vs. independent model testing following Pagel et al. 1994"


[links]
links = []