
title = "Toward a phylogenetic chronology of ancient Gaulish, Celtic, and Indo-European"

doi = "10.1073/pnas.1331158100"

abstract = """
Indo-European is the largest and best-documented language family in the world, yet the reconstruction of the Indo-European tree, first proposed in 1863, has remained controversial. Complications may include ascertainment bias when choosing the linguistic data, and disregard for the wave model of 1872 when attempting to reconstruct the tree. Essentially analogous problems were solved in evolutionary genetics by DNA sequencing and phylogenetic network methods, respectively. We now adapt these tools to linguistics, and analyze Indo-European language data, focusing on Celtic and in particular on the ancient Celtic language of Gaul (modern France), by using bilingual Gaulish–Latin inscriptions. Our phylogenetic network reveals an early split of Celtic within Indo-European. Interestingly, the next branching event separates Gaulish (Continental Celtic) from the British (Insular Celtic) languages, with Insular Celtic subsequently splitting into Brythonic (Welsh, Breton) and Goidelic (Irish and Scottish Gaelic). Taken together, the network thus suggests that the Celtic language arrived in the British Isles as a single wave (and then differentiated locally), rather than in the traditional two-wave scenario (‘‘P-Celtic’’ to Britain and ‘‘Q-Celtic’’ to Ireland). The phylogenetic network furthermore permits the estimation of time in analogy to genetics, and we obtain tentative dates for Indo-European at 8100 BC 6 1,900 years, and for the arrival of Celtic in Britain at 3200 BC 6 1,500 years. The phylogenetic method is easily executed by hand and promises to be an informative approach for many problems in historical linguistics.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Peter Forster",
    "Alfred Toth"
]

# parts of the world
groups = ["Indo-European"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@ForsterToth2003"

# type of study
type = ["network"]  # phylogenetic,phylogeography,macroevolutionary,trait

# short label of taxa "37 languages from.."
description = "12 Indo-European languages"

# data
[data]
    [data.lexicon]
    ntaxa = 12
    nchars = 35
    nsites = ""
    datatype = 'lexical cognates'
    source = ''
    items = ''
    comment = ''
    

# analysis information
[analysis]
    [analysis.network]
    tool = 'network'
    model = ''
    details = ""


[links]
phlorest = {}
lexibank = {}
links = []
