title = "A Phylogenetic Approach to the History of Cultural Practices"

doi = "10.1002/9781444302714.ch11"

abstract = """
Examination of the spatial and temporal distribution of cultural practices
can shed light on both their function and their development (Goody 1976: 2).
However, human societies cannot be treated as independent data poins in
statistical analyses of the distribution of cultural traits: any pattern
inferred by tallying societies in which the traits of interest occur runs the
risk of being spuriously inflated or deflated (e.g. Dow 1993).
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Laura Fortunato"]

# parts of the world
groups = ['Bantu']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Fortunato_2008"

# type of study
type = ['review']
framework = []
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
# analysis information
[analysis]
    
    notes = ""

[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []