title = "Testing cladistics on dialect networks and phyla (gallo-romance and southern italo-romance)."

doi = ""

abstract = """
This present work deliberately abandons the purpose of capturing the global resemblance between languages
and the ambition of giving a rational foundation to probability of changes in linguistics, to focus
instead on cladistic approach, which was applied to different dialects and data (gallo-romance, southern
italo-romance) through an original coding of philological derivations. Results show good congruence with
linguistic classification and provide new insight on how tackle various dialectological problems as
borrowings.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    'Antonella Gaillard-Corvaglia',
    'Jean-Léo Léonard',
    'Pierre Darlu'
]

# parts of the world
groups = ['Oïl Varieties', 'Southern Italo-Romance']

# bibkey citation in sources.bib
bibkey = "@GaillardCorvaglia2007"  # @xxxx

# type of study
type = ['phylogenetic']  # phylogenetic,dating,phylogeography,macroevolutionary,trait
framework = []

# short description of the study, one line.
description = "A test of phylogenetic methods on dialect data"

# data
[data]

    notes = ""
    
    [data.oil]
    ntaxa = 45
    nchars = 23
    nsites = "?"
    datatype = 'phonetic traits'
    source = '@ALF'
    items = ''
    comment = ''

    [data.sir]
    ntaxa = 21
    nchars = 20
    nsites = "?"
    datatype = 'phonetic traits'
    source = '@ALR'
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.paup_oil]
    tool = 'paup*'
    model = ''
    details = ""
    data = "@data.oil"

    [analysis.paup_sir]
    tool = 'paup*'
    model = ''
    details = ""
    data = "@data.sir"

    [analysis.consistency_index_oil]
    tool = 'paup*'
    model = 'CI'
    details = ""
    data = "@data.oil"
    
    [analysis.consistency_index_sir]
    tool = 'paup*'
    model = 'CI'
    details = ""
    data = "@data.sir"
    
    [analysis.retention_index_oil]
    tool = 'paup*'
    model = 'RI'
    details = ""
    data = "@data.oil"
    
    [analysis.retention_index_sir]
    tool = 'paup*'
    model = 'RI'
    details = ""
    data = "@data.sir"
    
    [analysis.rescaled_consistency_index_oil]
    tool = 'paup*'
    model = 'RC'
    details = ""
    data = "@data.oil"
    
    [analysis.rescaled_consistency_index_sir]
    tool = 'paup*'
    model = 'RC'
    details = ""
    data = "@data.sir"
    