title = "Indo-European phylogenetics with R"

doi = "10.1163/22125892-20201000"

abstract = """
The last twenty or so years have witnessed a dramatic increase in the use of computational methods for inferring
linguistic phylogenies. Although the results of this research have been controversial, the methods themselves are
an undeniable boon for historical and Indo-European linguistics, if for no other reason than that they allow the
field to pursue questions that were previously intractable. After a review of the advantages and disadvantages of
computational phylogenetic methods, I introduce the following methods of phylogenetic inference in R: maximum
parsimony; distance-based methods ( UPGMA and neighbor joining); and maximum likelihood estimation. I discuss the
strengths and weaknesses of each of these methods and in addition explicate various measures associated with
phylogenetic estimation, including homoplasy indices and bootstrapping. Phylogenetic inference is carried out on
the Indo-European dataset compiled by Don Ringe and Ann Taylor, which includes phonological, morphological, and
lexical characters.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ['David Goldstein']


# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Goldstein2020"  # @xxxx

# type of study
type = ['tutorial']
framework = ['distance', 'parsimony', 'likelihood']


# short description of the study, one line.
description = "Tutorial on Indo-European phylogenetics in R"

[links]
links = []
