title = "The Pleasures and Perils of Darwinizing Culture (with phylogenies)"

doi = "10.1162/biot.2007.2.4.360"

abstract = """
Current debates about “Darwinizing culture” have typically focused on the validity of memetics. In this paper we
argue that meme-like inheritance is not a necessary requirement for descent with modification. We suggest that an
alternative and more productive way of Darwinizing culture can be found in the application of phylogenetic
methods. We review recent work on cultural phylogenetics and outline six fundamental questions that can be
answered using the power and precision of quantitative phylogenetic methods. However, cultural evolution, like
biological evolution, is often far from tree-like. We discuss the problems reticulate evolution can cause for
phylogenetic analyses and suggest ways in which these problems can be overcome. Our solutions involve a
combination of new methods for the study of cultural evolution (network construction, reconciliation analysis, and
Bayesian mixture models), and the triangulation of different lines of historical evidence. Throughout we emphasize
that most debates about cultural phylogenies can only be settled by empirical research rather than armchair
speculation.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Russell D. Gray", "Simon J. Greenhill", "Robert M. Ross"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Gray2007"  # @xxxx

# type of study
type = ['review']  # phylogenetic,dating,phylogeography,macroevolutionary,trait
framework = []

# short description of the study, one line.
description = "Review article on the 'Pleasures and Perils of Darwinizing Culture (with phylogenies)'"

[links]
links = []