
title = "TransNewGuinea.org: An online database of New Guinea languages"

doi = "10.1371/journal.pone.0141563"

abstract = """
The island of New Guinea has the world’s highest linguistic diversity, with more than 900 languages divided into at least 23 distinct language families. This diversity includes the world’s third largest language family: Trans-New Guinea. However, the region is one of the world’s least well studied, and primary data is scattered across a wide range of publications and more often then not hidden in unpublished “gray” literature. The lack of primary research data on the New Guinea languages has been a major impediment to our understanding of these languages, and the history of the peoples in New Guinea. TransNewGuinea.org aims to collect data about these languages and place them online in a consistent format. This database will enable future research into the New Guinea languages with both traditional comparative linguistic methods and novel cutting-edge computational techniques. The long-term aim is to shed light into the prehistory of the peoples of New Guinea, and to understand why there is such major diversity in their languages.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Simon J. Greenhill"
]

# parts of the world
groups = ["Huon Peninsula"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Greenhill2015"

# type of study
type = ["phylogenetic", "network", "qresidual"]

# short label of taxa "37 languages from.."
taxa = "14 Huon Peninsula languages"

# data
[data]
    [data.lexicon]
    ntaxa = 14
    nchars = 100
    nsites = 391
    datatype = 'lexical cognates'
    source = '@McElhanon1967'
    items = 'swadesh100'
    comment = ''

## Methods:
# analysis information
[analysis]
    [analysis.network]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""

    [analysis.qresidual]
    tool = 'splitstree'
    model = ''
    details = ""

    [analysis.tree1]
    tool = 'beast2'
    model = 'ctmc+strict'
    details = ""

    [analysis.tree2]
    tool = 'beast2'
    model = 'ctmc+gamma+strict'
    details = ""

    [analysis.tree3]
    tool = 'beast2'
    model = 'covarion+strict'
    details = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/greenhill2015" }
lexibank = { title = "Lexibank Dataset", link = "" }
links = []
