title = "The shape and tempo of language evolution"

doi = "10.1098/rspb.2010.0051"

abstract = """
There are approximately 7000 languages spoken in the world today. This diversity reflects the legacy of thousands of years of cultural evolution. How far back we can trace this history depends largely on the rate at which the different components of language evolve. Rates of lexical evolution are widely thought to impose an upper limit of 6000 – 10 000 years on reliably identifying language relationships. In contrast, it has been argued that certain structural elements of language are much more stable. Just as biologists use highly conserved genes to uncover the deepest branches in the tree of life, highly stable linguistic features hold the promise of identifying deep relationships between the world’s languages. Here, we present the first global network of languages based on this typological information. We evaluate the relative evolution- ary rates of both typological and lexical features in the Austronesian and Indo-European language families. The first indications are that typological features evolve at similar rates to basic vocabulary but their evolution is substantially less tree-like. Our results suggest that, while rates of vocabulary change are correlated between the two language families, the rates of evolution of typological features and structural subtypes show no consistent relationship across families.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Simon J. Greenhill", "Quentin D. Atkinson", "Andrew Meade", "Russell D. Gray"]

# parts of the world
groups = ['global', 'Austronesian', 'Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Greenhill2010b"

# type of study
type = ['network', 'trait']  # phylogenetic,dating,phylogeography,macroevolutionary,trait,review,tutorial
framework = []

# short description of the study, one line.
description = "Evaluation of the relative evolutionary rates of both typological and lexical features in the Austronesian and Indo-European language families"

# data
[data]

    notes = ""
    
    [data.worldwide]
    ntaxa = 99
    nchars = 138
    nsites = 138
    datatype = 'structural features'
    source = '@WALS'
    items = ''
    comment = ''

    [data.wals_austronesian]
    ntaxa = 20
    nchars = 138
    nsites = 138
    datatype = 'structural features'
    source = '@WALS'
    items = ''
    comment = ''

    [data.wals_indoeuropean]
    ntaxa = 20
    nchars = 138
    nsites = 138
    datatype = 'structural features'
    source = '@WALS'
    items = ''
    comment = ''

    [data.lexical_austronesian]
    ntaxa = 20
    nchars = 210
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@ABVD'
    items = ''
    comment = ''

    [data.lexical_indoeuropean]
    ntaxa = 20
    nchars = 200
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Dyen1992'
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.nnet_worldwide]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.worldwide"

    [analysis.nnet_austronesian_lexicon]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.lexical_austronesian"

    [analysis.nnet_austronesian_grammar]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.wals_austronesian"

    [analysis.nnet_indoeuropean_lexicon]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.lexical_indoeuropean"

    [analysis.nnet_indoeuropean_grammar]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.wals_indoeuropean"

    [analysis.ri_austronesian_lexicon]
    tool = 'paup*'
    model = 'retention index'
    details = ""
    data = "@data.lexical_austronesian"

    [analysis.ri_austronesian_grammar]
    tool = 'paup*'
    model = 'retention index'
    details = ""
    data = "@data.wals_austronesian"

    [analysis.ri_indoeuropean_lexicon]
    tool = 'paup*'
    model = 'retention index'
    details = ""
    data = "@data.lexical_indoeuropean"

    [analysis.ri_indoeuropean_grammar]
    tool = 'paup*'
    model = 'retention index'
    details = ""
    data = "@data.wals_indoeuropean"

    [analysis.tree_austronesian_lexicon]
    tool = 'bayesphylogenies'
    model = 'm2p'
    details = ""
    data = "@data.lexical_austronesian"

    [analysis.tree_austronesian_grammar]
    tool = 'bayesphylogenies'
    model = 'm2p'
    details = ""
    data = "@data.wals_austronesian"

    [analysis.tree_indoeuropean_lexicon]
    tool = 'bayesphylogenies'
    model = 'm2p'
    details = ""
    data = "@data.lexical_indoeuropean"

    [analysis.tree_indoeuropean_grammar]
    tool = 'bayesphylogenies'
    model = 'm2p'
    details = ""
    data = "@data.wals_indoeuropean"
    
    [analysis.rates_austronesian_lexicon]
    tool = 'bayestraits'
    model = 'multistate'
    details = ""
    data = "@data.lexical_austronesian"

    [analysis.rates_austronesian_grammar]
    tool = 'bayestraits'
    model = 'multistate'
    details = ""
    data = "@data.wals_austronesian"

    [analysis.rates_indoeuropean_lexicon]
    tool = 'bayestraits'
    model = 'multistate'
    details = ""
    data = "@data.lexical_indoeuropean"

    [analysis.rates_indoeuropean_grammar]
    tool = 'bayestraits'
    model = 'multistate'
    details = ""
    data = "@data.wals_indoeuropean"