title = "Austronesian language phylogenies: Myths and misconceptions about Bayesian computational methods"

doi = ""

abstract = """
Historical linguistics has never been particularly intimate with computers. The first wave of computational historical linguistics—lexicostatistics—was developed in the 1950s (Swadesh 1952; Lees 1953) and quickly applied to language groups around the world from Indo-European to Austronesian (Lees 1953; Hymes 1960; Embleton 1986). However, critics were quick to point out the problems caused by assuming a single constant rate of lexical replacement and repeatedly noted the erroneous results that this produced (Hoijer 1956; Bergsland and Vogt 1962; Blust 1981; McMahon and McMahon 2006). As a consequence of these critiques lexicostatistics has been widely rejected by mainstream historical linguists (Campbell 2004).
The last few years have seen a second wave of computational approaches entering historical linguistics: phylogenetic methods. These techniques, drawn from evolutionary biology, have been used to investigate some provocative and controversial claims about human prehistory.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    'Simon J. Greenhill', 'Russell D. Gray'
]

# parts of the world
groups = ['Austronesian']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Greenhill2009"  # @xxxx

# type of study
type = ['phylogenetic', 'dating']  # phylogenetic,dating,phylogeography,macroevolutionary,trait
framework = []

# short description of the study, one line.
description = "Tutorial paper on language phylogenies with focus on Austronesian"

# data
[data]

    notes = ""
    
    [data.lexicon]
    ntaxa = 400
    nchars = 210
    nsites = 34440
    datatype = 'lexical cognates'
    source = '@Greenhilletal2008'
    items = 'swadesh200'
    comment = ''
    
    [data.modelling]
    ntaxa = 33
    nchars = 3
    nsites = 3
    datatype = 'lexical cognates'
    source = '@Greenhilletal2008'
    items = 'swadesh200'
    comment = "'earth/soil' mapped onto a tree of the Central Pacific subfamily (the expanded form of Figure 2). Cognate set A (colored white) reflects forms like Tongan kelekele, Samoan 'ele'ele and Fijian (Bau) qele. Cognate set B (colored gray) reflects forms like the Tahitian repo and Hawaiian lepo. Cognate set C (colored black) reflects forms like Vaeakau-Taumako's pela."


# date calibrations
[calibrations]

    [calibration.PMP]
    taxa = ["mala1545"]
    age = "uniform(3600, 4500)"
    units = "y2000"
    description = ""


    [calibration.protooceanic]
    taxa = ["ocea1241"]
    age = "uniform(3200, 3600)"
    units = "y2000"
    description = ""


    [calibration.epolynesian]
    taxa = ["east2449"]
    age = "uniform(1150, 1800)"
    units = "y2000"
    description = ""


    [calibration.protochamic]
    taxa = ["cham1330"]
    age = "uniform(1800, 2500)"
    units = "y2000"
    description = ""


    [calibration.protomalagasy]
    taxa = ["mala1537"]
    age = "uniform(1100, 1300)"
    units = "y2000"
    description = ""


    [calibration.protojavanese]
    taxa = ["java1254"]
    age = "uniform(1100, 1300)"
    units = "y2000"
    description = ""


    [calibration.protorsc]
    taxa = ["reef1242"]
    age = "uniform(3000, 3150)"
    units = "y2000"
    description = ""


    [calibration.malayicchamic]
    taxa = ["mala1538", "cham1330"]
    age = "uniform(2000, 3000)"
    units = "y2000"
    description = ""


    [calibration.micronesian]
    taxa = ["micr1243"]
    age = "uniform(1900, 2200)"
    units = "y2000"
    description = ""


    [calibration.tuvtok]
    taxa = ["tuva1244", "toke1240"]
    age = "uniform(1000, 2000)"
    units = "y2000"
    description = ""


    [calibration.OldJavanese]
    taxa = ["mode1251"]
    age = "uniform(700, 1200)"
    units = "y2000"
    description = ""


    [calibration.OldChinese]
    taxa = ["oldc1244"]
    age = "uniform(2300, 2900)"
    units = "y2000"
    description = ""


    [calibration.Favorlang]
    taxa = ["babu1240"]
    age = "uniform(346, 384)"
    units = "y2000"
    description = ""


    [calibration.Siraya]
    taxa = ["sira1267"]
    age = "uniform(346, 384)"
    units = "y2000"
    description = ""


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = 'bayesphylogenies'
    model = 'm2p+gamma'
    details = ""

    [analysis.r8s]
    tool = 'r8s'
    model = ''
    details = ""

    [analysis.bayestraits]
    tool = 'bayestraits'
    model = 'multistate'
    details = "ASR of three cognate sets as example"
    data = '@data.modelling'


[inferredages]
    
    notes = ""
    
    [inferredage.proto_austronesian]
    taxa = ['aust1307']
    age = "5310"
    units = "y2000"
    notes = ""

    [inferredage.proto_malayo_polynesian]
    taxa = ['mala1545']
    age = "4240"
    units = "y2000"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []