
title = "Bantu expansion shows that habitat alters the route and pace of human dispersals"

doi = "10.1073/pnas.1503793112"

abstract = """
Unlike most other biological species, humans can use cultural innovations to occupy a range of environments, raising the intriguing question of whether human migrations move relatively independently of habitat or show preferences for familiar ones. The Bantu expansion that swept out of West Central Africa beginning ∼5,000 y ago is one of the most influential cultural events of its kind, eventually spreading over a vast geographical area a new way of life in which farming played an increasingly important role. We use a new dated phylogeny of ∼400 Bantu languages to show that migrating Bantu-speaking populations did not expand from their ancestral homeland in a “random walk” but, rather, followed emerging savannah corridors, with rainforest habitats repeatedly imposing temporal barriers to movement. When populations did move from savannah into rainforest, rates of migration were slowed, delaying the occupation of the rainforest by on average 300 y, compared with similar migratory movements exclusively within savannah or within rainforest by established rainforest populations. Despite unmatched abilities to produce innovations culturally, unfamiliar habitats significantly alter the route and pace of human dispersals.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Rebecca Grollemund",
    "Simon Branford",
    "Koen Bostoen",
    "Andrew Meade",
    "Chris Venditti",
    "Mark Pagel"
]

# parts of the world
groups = ["Bantu"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@grollemund2015"

# type of study
type = ["phylogenetic", "phylogeography"]  # phylogenetic,phylogeography,macroevolutionary,trait

# short label of taxa "37 languages from.."
taxa = "425 Bantu languages"

# data
[data]
    [data.lexicon]
    ntaxa = 425
    nchars = 100
    nsites = 3859
    datatype = 'lexical cognates'
    source = '@ALGAB'
    
## Methods:

# analysis information
[analysis]
    [analysis.tree]
    tool = 'bayesphylogenies'
    model = 'm1p+covarion+relaxed'
    details = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/grollemund_et_al2015" }
lexibank = { title = "Lexibank Dataset", link = "https://github.com/lexibank/grollemundbantu" }
links = []
