title = "Parametric Comparison and Language Taxonomy"

doi = "10.1093/acprof:oso/9780199272129.003.0010"

abstract = """
It is still a widely held opinion that the contribution of formal syntactic
theories to modern linguistics is essentially focused on synchronic
generalizations and that it does not extend to the most classical problems
of the historical paradigm. Such a belief is beginning to fade away as a
consequence of increased work in diachronic syntax (e.g. Roberts 1993, the
contributions contained in van Kemenade and Vincent 1997, Lightfoot 1999,
Longobardi 2001b among others). In this work we will argue that the
generative theory of syntactic parameters might interestingly renovate
another stronghold of the historical study of language, phylogenetic
taxonomy, and undermine the Humboldtian received distinction between the
latter and grammatical typology.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Cristina Guardiano", "Giuseppe Longobardi"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@GUARDIANO_2005"

# type of study
type = ['phylogenetic']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['distance'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.parameter]
    ntaxa = 15
    nchars = 30
    nsites = 30
    datatype = 'syntactical features'
    source = ''
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.visualisation]
    tool = 'manual'
    model = ''
    details = ""
    data = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []