title = "Divergence and contact in Southern Bantu language and population history: A new phylogeny in cross-disciplinary perspective"

doi = "10.1163/22105832-bja10022"

abstract = """
In this paper we present a new, lexicon-based phylogeny of 34 Southern Bantu languages, and
combine it with previous insights from linguistics, archaeology, and genet- ics to study the
history of Southern Bantu languages and their speakers. Our phylogeny shows all Southern Bantu
languages to derive from a single, direct ancestor, which contrasts with archaeological evidence
indicating separate migrations of Bantu speak- ers into southern Africa. This suggests that the
Bantu languages spoken by the first migrants became extinct, and the ancestor of present-day
Southern Bantu languages only emerged in southern Africa during the second millennium ce. We also
map the distribution of previously established or suspected Khoisan-derived linguistic features in
Southern Bantu languages onto this phylogeny. Evidence for intensive contact with speakers of
Khoisan languages also comes from population genetics, which shows that Khoisan linguistic
influence is mainly seen in languages spoken by populations dis- playing a higher degree of
genetic admixture.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    'Hilde Gunnink',
    'Natalia Chousou-Polydouri',
    'Koen Bostoen',
]

# parts of the world
groups = ['Bantu']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Gunnink2022"  # @xxxx

# type of study
type = ['phylogenetic', 'trait']  # phylogenetic,dating,phylogeography,macroevolutionary,trait

# short label of taxa "37 languages from.."
taxa = "79 Bantu languages with a focus on Southern Bantu"

# data
[data]

    notes = ""
    
    [data.lexicon]
    ntaxa = 81
    nchars = 100
    nsites = 1456   # 1431 listed in paper
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh100'
    comment = ''

    [data.grammar]
    ntaxa = 79
    nchars = 6
    nsites = 6
    datatype = 'structural features'
    source = ''
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = 'mrbayes'
    model = 'restrictionsite+noabsencesites'
    details = "The evolution of the characters was modeled with a simple binary (restriction site) model (with “noabsencesites” ascertainment correction, since all absent characters are not observable"

    [analysis.asr]
    tool = 'mesquite'
    model = 'asr+parsimony'
    details = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/gunnink_et_al2022" }
cldf = { title = "CLDF Dataset", link = "http://doi.org/10.17605/OSF.IO/7WAUS" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []