title = "Splits or waves? Trees or webs? How divergence measures and network analysis can unravel language histories"

doi = "10.1098/rstb.2010.0099"

abstract = """
Linguists have traditionally represented patterns of divergence within a language family in terms
of either a 'splits' model, corresponding to a branching family tree structure, or the wave model,
resulting in a (dialect) continuum. Recent phylogenetic analyses, however, have tended to assume
the former as a viable idealization also for the latter. But the contrast matters, for it typically
reflects different processes in the real world: speaker populations either separated by migrations,
or expanding over continuous territory. Since history often leaves a complex of both patterns
within the same language family, ideally we need a single model to capture both, and tease apart
the respective contributions of each. The 'network' type of phylogenetic method offers this, so we
review recent applications to language data. Most have used lexical data, encoded as binary or
multi-state characters. We look instead at continuous distance measures of divergence in phonetics.
Our output networks combine branch and continuum-like signals in ways that correspond well to
known histories (illustrated for Germanic, and particularly English). We thus challenge the
traditional insistence on shared innovations, setting out a new, principled explanation for why
complex language histories can emerge correctly from distance measures, despite shared retentions
and parallel innovations.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Paul Heggarty", "Warren Maguire", "April McMahon"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Heggarty_2010"

# type of study
type = ['phylogenetic']
framework = ['network'] # distance,parsimony,likelihood,bayesian,network,statistical,other

# data
[data]

    notes = ""
    
    [data.germanic]
    ntaxa = 52
    nchars = 1
    nsites = 1
    datatype = 'phonetic distance'
    source = ''
    items = ''
    comment = ''

    [data.english]
    ntaxa = 40
    nchars = 1
    nsites = 1
    datatype = 'phonetic distance'
    source = ''
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.germanic]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.germanic"

    [analysis.english]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "@data.english"



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []