
title = "Detecting Regular Sound Changes in Linguistics as Events of Concerted Evolution"

doi = "10.1016/j.cub.2014.10.064"

abstract = """
Concerted evolution is normally used to describe parallel changes
at different sites in a genome, but it is also observed in languages where a
specific phoneme changes to the same other phoneme in many words in the lexicon—a
phenomenon known as regular sound change. We develop a general statistical model
that can detect concerted changes in aligned sequence data and apply it to study
regular sound changes in the Turkic language family. Results: Linguistic
evolution, unlike the genetic substitutional process, is dominated by events of
concerted evolutionary change. Our model identified more than 70 historical
events of regular sound change that occurred throughout the evolution of the
Turkic language family, while simultaneously inferring a dated phylogenetic tree.
Including regular sound changes yielded an approximately 4-fold improvement in
the characterization of linguistic change over a simpler model of sporadic
change, improved phylogenetic inference, and returned more reliable and plausible
dates for events on the phylogenies. The historical timings of the concerted
changes closely follow a Poisson process model, and the sound transition networks
derived from our model mirror linguistic expectations. Conclusions: We
demonstrate that a model with no prior knowledge of complex concerted or regular
changes can nevertheless infer the historical timings and genealogical placements
of events of concerted change from the signals left in contemporary data. Our
model can be applied wherever discrete elements—such as genes, words, cultural
trends, technologies, or morphological traits—can change in parallel within an
organism or other evolving group.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Daniel J. Hruschka",
    "Simon Branford",
    "Eric D. Smith",
    "Jon Wilkins",
    "Andrew Meade",
    "Mark Pagel",
    "Tanmoy Bhattacharya"
]

# parts of the world
groups = ["Turkic"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Hruschka2015"

# type of study
type = ['phylogenetic', 'dating']
framework = ['bayesian']

# short label of taxa "37 languages from.."
description = "26 Turkic languages"

# data
[data]
    [data.lexicon]
    ntaxa = 26
    nchars = ""
    nsites = ""
    datatype = 'lexical cognates'
    source = ''
    items = ''
    comment = ''


[calibration]
    notes = "and includes the current dates of dictionaries for each of the contemporary languages"

    [calibration.SeljukConquest]
    taxa = ["oghu1243"]
    age = "uniform(300, 700)"
    units = "ad"
    description = "the Seljuk conquest of Baghdad (1055 CE), which is likely the latest date for divergence of Seljuk-derived languages (Turkish, Azeri, Gagauz) from other Oghuz languages (Turkmen), the earliest likely date being 985 CE"


# analysis information
[analysis]
    [analysis.regular]
    tool = 'bayesphylogenies'
    model = 'mk+regular'
    details = "The sporadic sound changes are modeled as a continuous-time Markov process, widely used in models of DNA or protein sequence evolution, where in place of the usual 4 3 4or203 20 matrices of nucleotide or amino acid transitions, we erect a 62 3 62 sound transition rate matrix, denoted Qs (Supplemental Experimental Procedures). We estimate the elements of Qs from the data employing a reversible-jump Markov chain Monte Carlo (RJ-MCMC) procedure described elsewhere [16] that allows the large number of potential parameters to be reduced to a potentially far smaller set of statistically distinct parameters, and without loss of statistical accuracy or prior knowledge on the part of investigators. We find that nine distinct rate classes, empirically estimated from the data, plus a category of rates estimated to be zero, are sufficient for the Turkic data. "

    [analysis.regular_and_sporadic]
    tool = 'bayesphylogenies'
    model = 'mk+regular+sporadic'
    details = "Regular sound changes of the general form denoting the ith sound changing to the jth are modeled in a stochastic matrix Qr that takes the form of an identity matrix with the ith diagonal element interchanged with the off diagonal position (ji). Premultiplication of any stochastic matrix Q (e.g., that in PðDjQs; tÞ) by such a matrix is equivalent to adding all elements qi1, qi2,.qik to the corresponding values of qj1, qj2.qjk and then zeroing out the qi1, qi2,.qik. We then use a different RJ-MCMC procedure to propose possible Qr matrices in branches of the phylogenetic tree, thereby allowing regular changes to occur or not occur on a branch-specific basis."


[inferredages]
    
    notes = ""
    
    [inferredage.sporadic]
    taxa = ['turk1311']
    age = "hpd(4408, 3279, 5993)"
    units = "y2000"
    details = "2408 BCE, with 95% credible intervals of 3993–1279 BCE;"

    [inferredage.regular]
    taxa = ['turk1311']
    age = "hpd(2204, 2605, 1919)"
    units = "y2000"
    details = "204 BCE, with 95% credible intervals of 605 BCE–81 CE"


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
links = []

