title = "Modelling admixture across language levels to evaluate deep history claims"

doi = "10.1093/jole/lzad002"

abstract = """
The so-called 'Altaic' languages have been subject of debate for over 200 years. An array of different data sets
have been used to investigate the genealogical relationships between them, but the controversy persists. The new
data with a high potential for such cases in historical linguistics are structural features, which are sometimes
declared to be prone to borrowing and discarded from the very beginning and at other times considered to have an
especially precise historical signal reaching further back in time than other types of linguistic data. We
investigate the performance of typological features across different domains of language by using an admixture
model from genetics. As implemented in the software STRUCTURE, this model allows us to account for both a
genealogical and an areal signal in the data. Our analysis shows that morphological features have the strongest
genealogical signal and syntactic features diffuse most easily. When using only morphological structural data,
the model is able to correctly identify three language families: Turkic, Mongolic, and Tungusic, whereas Japonic
and Koreanic languages are assigned the same ancestry.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Nataliia Hübler", "Simon J. Greenhill"]

# parts of the world
groups = ['Tungusic', 'Mongolian', 'Japonic', 'Koreanic', 'Turkic']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@H_bler_2022"

# type of study
type = ['structure']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['statistical', 'likelihood',] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = "Investigates the performance of typological features across different domains of language by using an admixture model from genetics to assess admixture"

# data
[data]

    notes = ""
    
    [data.structure]
    ntaxa = 60
    nchars = 171
    nsites = 60
    datatype = 'structural features'
    source = '@Huebler_2022'
    items = ''
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.structure]
    tool = 'structure'
    model = ''
    details = ""
    data = ""



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []