title = "Valence-dependent mutation in lexical evolution"

doi = "10.1038/s41562-022-01483-8"

abstract = """
A central goal of linguistics is to understand how words evolve. Past research has found that macro-level
factors such as frequency of word usage and population size explain the pace of lexical evolution. Here we
focus on cognitive and affective factors, testing whether valence (positivitynegativity) explains lexical
evolution rates. Using estimates of cognate replacement rates for 200 concepts on an Indo-European language
tree spanning six to ten millennia, we find that negative valence correlates with faster cognate
replacement. This association holds when controlling for frequency of use, and follow-up analyses show that
it is most robust for adjectives ('dirty' versus 'clean'; 'bad' versus 'good'); it does not consistently
reach statistical significance for verbs, and never reaches significance for nouns. We also present
experiments showing that individuals are more likely to replace words for negative versus positive
concepts. Our findings suggest that emotional valence affects micro-level guided variation, which drives
macro-level valence-dependent mutation in adjectives.

"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Joshua Conrad Jackson", "Kristen Lindquist", "Ryan Drabble", "Quentin D. Atkinson", "Joseph Watts"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Jackson_2022"

# type of study
type = ['macroevolutionary']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = [] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = "uses rate data from Pagel et al."
    
    [data.pagel]
    ntaxa = 87
    nchars = 200
    nsites = 200
    datatype = 'rates'
    source = '@Pagel_2007'
    items = ''
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.regression]
    tool = 'r'
    model = ''
    details = ""
    data = ""



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []