title = "Computational historical linguistics"

doi = "10.1515/tl-2019-0011"

abstract = """
Computational approaches to historical linguistics have been proposed
for half a century. Within the last decade, this line of research has received a
major boost, owing both to the transfer of ideas and software from computational
biology and to the release of several large electronic data resources suitable for
systematic comparative work. In this article, some of the central research topics of this new wave of 
computational historical linguistics are introduced and discussed. These are automatic
assessment of genetic relatedness, automatic cognate detection, phylogenetic infer-
ence and ancestral state reconstruction. They will be demonstrated by means of a
case study of automatically reconstructing a Proto-Romance word list from lexical
data of 50 modern Romance languages and dialects. The results illustrate both
the strengths and the weaknesses of the current state of the art of automating the
comparative method.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Gerhard Jäger"]

# parts of the world
groups = ['global']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@J_ger_2019"

# type of study
type = ['review']
framework = ['other']


# short description of the study, one line.
description = "Review article on computational historical linguistics"


