title = "Phylogenetic Typology"

doi = "10.3389/fpsyg.2021.682132"

abstract = """
In this article we propose a novel method to estimate the frequency distribution of linguistic variables while controlling for statistical non-independence due to shared ancestry. Unlike previous approaches, our technique uses all available data, from language families large and small as well as from isolates, while controlling for different degrees of relatedness on a continuous scale estimated from the data. Our approach involves three steps: First, distributions of phylogenies are inferred from lexical data. Second, these phylogenies are used as part of a statistical model to estimate transition rates between parameter states. Finally, the long-term equilibrium of the resulting Markov process is computed. As a case study, we investigate a series of potential word-order correlations across the languages of the world.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Gerhard Jäger", "Johannes Wahle"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@J_ger_2021"

# type of study
type = ['trait']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.wals]
    ntaxa = 1626
    nchars = 8
    nsites = 8
    datatype = 'structural features'
    source = '@WALS'
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.jaeger2018]
    source = '@Jaeger2018'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.traits]
    tool = 'custom'
    model = ''
    details = "pairwise comparisons"
    data = ""
    times = 28


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []