title = "The evolutionary dynamics of grammatical gender in Torricelli languages"

doi = "10.1515/stuf-2024-2010"

abstract = """
Grammatical gender in New Guinea is an often neglected area in typological research, even
though it is extremely diverse. For example, in New Guinea, some languages have grammatical
gender systems with two sex-based categories, more than four gender-indexing targets, and no
gender marking on nouns, while some languages have grammatical gender systems with much more
categories, which are only marginally sex-based. This paper infers the processes of development
and change of grammatical gender in Torricelli languages from two perspectives. First, it
synthesizes the available data in the existing literature and hypothesizes the evolutionary
pathway of gender systems in Torricelli languages. Nineteen Torricelli languages are selected
as a representative coverage of the 55 Torricelli languages listed in Glottolog within the
limits of the available documentation. These languages are then coded based on 6
presence-absence features relating to gender marking on verbs, adjectives, nouns, numerals,
pronouns, and demonstratives. Second, it conducts an analysis with phylogenetic comparative
methods to provide a quantitative assessment of the evolutionary possibilities for gender
systems in Torricelli languages. The preliminary results show that gender is likely marked at
the root of Torricelli languages, with pronouns and verbs being at the core of the system. This
is in agreement with trends reflecting the evolution of gender systems in languages across the
world.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Jose A. Jódar-Sánchez", "Marc Allassonnière-Tang"]

# parts of the world
groups = ['Toricelli']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@J_dar_S_nchez_2024"

# type of study
type = ['asr', 'trait']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['likelihood', 'bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.toricelli]
    ntaxa = 19
    nchars = 6
    nsites = 6
    datatype = 'structural features'
    source = ''
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.global]
    source = '@Bouckaert_2022'
    comment = 'toricelli group extracted from global tree'


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.ace]
    tool = 'phytools'
    model = 'ER'
    details = ""
    data = ""
    times = 5412  # 6 * 902 trees

    [analysis.scm]
    tool = 'phytools'
    model = 'simmap'
    details = ""
    data = ""
    times = 5412  # 6 * 902 trees

    [analysis.rjhp]
    tool = 'bayestraits'
    model = 'mcmc+rjhp'
    details = ""
    data = ""
    times = 10  # ten pairs of traits? unclear about others.

 

[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = ["https://osf.io/gafs4/"]