title = "Rapid radiation of the inner Indo-European languages: an advanced approach to Indo-European lexicostatistics"

doi = "10.1515/ling-2020-0060"

abstract = """
In this article we present a new reconstruction of Indo-European phylogeny based on 13 110-item basic wordlists for
protolanguages of IE subgroups (Proto-Germanic, Proto-Slavic, etc.) or ancient languages of the corresponding
subgroups (Hittite, Ancient Greek, etc.). We apply reasonably formal techniques of linguistic data collection and
post-processing (onomasiological reconstruction, derivational drift elimination, homoplastic optimization) that
have been recently proposed or specially developed for the present study. We use sequential phylogenetic workflow
and obtain a consensus tree based on several algorithms (Bayesian inference, maximum parsimony, neighbor joining;
without topological constraints applied). The resulting tree topology and datings are entirely compatible with
established expert views. Our main finding is the multifurcation of the Inner IE clade into four branches ca.
3357–2162 BC: (1) Greek-Armenian, (2) Albanian, (3) Italic-Germanic-Celtic, (4) Balto-Slavic–Indo-Iranian. The
proposed radiation scenario may be reconciled with diverse opinions on Inner IE branchings previously expressed by
Indo-Europeanists.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Alexei S. Kassian",
    "Mikhail Zhivlov",
    "George Starostin",
    "Artem A. Trofimov",
    "Petr A. Kocharov",
    "Anna Kuritsyna",
    "Mikhail N. Saenko"
]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Kassian2021"  # @xxxx

# type of study
type = ['phylogenetic']
framework = ['bayesian', 'parsimony', 'statistical']


# short description of the study, one line.
description = "Reconstruction of Indo-European"

# data
[data]

    notes = ""

    [data.gled]
    ntaxa = 13
    nchars = 110
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@GLED'
    items = ''
    comment = ''

    [data.gled_stage1]
    ntaxa = 13
    nchars = 110
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@GLED'
    items = ''
    comment = 'Stage-1. High-quality dataset with traditional root cognacy.'

    [data.gled_stage2]
    ntaxa = 13
    nchars = 110
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@GLED'
    items = ''
    comment = 'Stage-2. Dataset without derivational drift.'
    
    [data.gled_stage3]
    ntaxa = 13
    nchars = 110
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@GLED'
    items = ''
    comment = 'Stage-3. Homoplasy-optimized dataset'



        
# date calibrations
[calibrations]

    notes = ""

    [calibration.OldHittite]
    taxa = ['hitt1242']
    age = "uniform(3600, 3450)"
    units = "bp" 
    description = "OldHittite	1650–1500 bc	1550 bc"

    [calibration.TocharianB]
    taxa = ['tokh1243']
    age = "uniform(1550, 1050)"
    units = "bp" 
    description = "TocharianB	400–900 ad	650 ad"

    [calibration.AncientAtticGreek]
    taxa = ['anci1242']
    age = "2325"
    units = "bp" 
    description = "AncientAtticGreek	375 bc	375 bc"

    [calibration.ClassicalArmenian]
    taxa = ['clas1249']
    age = "uniform(1550, 1450)"
    units = "bp" 
    description = "ClassicalArmenian	400–500 ad	450 ad"

    [calibration.Albanian]
    taxa = ['alba1267']
    age = "0"
    units = "bp" 
    description = "Albanian	1950 ad	1950 ad"

    [calibration.ArchaicLatin]
    taxa = ["lati1261"]
    age = "2150"
    units = "bp" 
    description = "ArchaicLatin	200 bc	200 bc"

    [calibration.OldIrish]
    taxa = ["oldi1245"]
    age = "uniform(1250, 1050)"
    units = "bp" 
    description = "OldIrish	700–900 ad	800 ad"

    [calibration.Proto-Brittonic]
    taxa = ['bryt1239']
    age = "uniform(1650, 1350)"
    units = "bp" 
    description = "Proto-Brittonic	300–600 ad	450 ad"

    [calibration.Proto-Germanic]
    taxa = ['germ1287']
    age = "uniform(2450, 2250)"
    units = "bp" 
    description = "Proto-Germanic	500–300 bc	400 bc"

    [calibration.Proto-Slavic]
    taxa = ['slav1255']
    age = "uniform(1949, 1650)"
    units = "bp" 
    description = "Proto-Slavic	1–300 ad	100 ad"

    [calibration.Proto-EastBaltic]
    taxa = ['east2280']
    age = "uniform(2350, 1951)"
    units = "bp" 
    description = "Proto-EastBaltic	400–1 bc	200 bc"

    [calibration.OldIndicAtharvaveda]
    taxa = ['sans1269']
    age = "uniform(3150, 2950)"
    units = "bp" 
    description = "OldIndicAtharvaveda	1200–1000 bc	1100 bc"

    [calibration.Proto-Iranian]
    taxa = ['iran1269']
    age = "uniform(3450, 2950)"
    units = "bp" 
    description = "Proto-Iranian	1500–1000 bc	1300 bc"

    [calibration.Proto-Samoyed]
    taxa = ['samo1298']
    age = "uniform(2900, 2700)"
    units = "bp" 
    description = "Proto-Samoyed	950–750 bc	800 bc"

    [calibration.Proto-Indo-European]
    taxa = ['indo1319']
    age = "uniform(5450, 10450)"
    units = "bp" 
    description = "Proto-Indo-European	3500–8500 bc"


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree_nj_gled_stage1]
    tool = 'starling'
    model = 'StarlingNJ'
    details = ""
    data = "@data.gled_stage1"

    [analysis.tree_bayesian_gled_stage1]
    tool = 'mrbayes'
    model = 'F81+covarion+gamma+restriction+relaxedTK02'
    details = ""
    data = "@data.gled_stage1"

    [analysis.tree_parsimony_gled_stage1]
    tool = 'tnt'
    model = ''
    details = ""
    data = "@data.gled_stage1"

    [analysis.tree_nj_gled_stage2]
    tool = 'starling'
    model = 'StarlingNJ'
    details = ""
    data = "@data.gled_stage2"

    [analysis.tree_bayesian_gled_stage2]
    tool = 'mrbayes'
    model = 'F81+covarion+gamma+restriction+relaxedTK02'
    details = ""
    data = "@data.gled_stage2"

    [analysis.tree_parsimony_gled_stage2]
    tool = 'tnt'
    model = ''
    details = ""
    data = "@data.gled_stage2"

    [analysis.tree_nj_gled_stage3]
    tool = 'starling'
    model = 'StarlingNJ'
    details = ""
    data = "@data.gled_stage3"

    [analysis.tree_bayesian_gled_stage3]
    tool = 'mrbayes'
    model = 'F81+covarion+gamma+restriction+relaxedTK02'
    details = ""
    data = "@data.gled_stage3"

    [analysis.tree_parsimony_gled_stage3]
    tool = 'tnt'
    model = ''
    details = ""
    data = "@data.gled_stage3"




[inferredages]
    
    notes = ""


    [inferredage.Stage2_AnatolianSplit]
    taxa = ["indo1319"]
    units = "bp" # before present
    age = "hpd(5697, 6264, 5400)"
    notes = "Anatolian split-off (root): 4314-3450 bc (mean 3747 bc)"

    [inferredage.Stage2_TocharianSplit]
    taxa = ["tokh1241"]
    units = "bp" # before present
    age = "hpd(4924, 5771, 4049)"
    notes = "Tocharian split-off: 3821–2099 bc (mean 2974 bc)"

    [inferredage.Stage2_InnerIEBreakUp]
    taxa = ["clas1257"]
    units = "bp" # before present
    age = "hpd(4752, 5522, 4095)"
    notes = "Inner IE break-up: 3572–2145 bc (mean 2802 bc)"

    [inferredage.Stage2_GreekArmenianBreakUp]
    taxa = ["grae1234", "arme1241"]
    units = "bp" # before present
    age = "hpd(3936, 4697, 3214)"
    notes = "Greek-Armenian break-up: 2747–1264 bc (mean 1986 bc)"

    [inferredage.Stage2_ItalicGermanicCelticBreakUp]
    taxa = ["ital1284", "germ1287", "celt1248"]
    units = "bp" # before present
    age = "hpd(4078, 4775, 3393)"
    notes = "Italic-Germanic-Celtic break-up: 2825–1443 bc (mean 2128 bc)"

    [inferredage.Stage2_InsularCelticBreakUp]
    taxa = ["insu1254"]
    units = "bp" # before present
    age = "hpd(2167, 2555, 1812)"
    notes = "Insular Celtic break-up: 605bc–138ad (mean 217 bc)"

    [inferredage.Stage2_BaltoSlavicIndoIranianBreakUp]
    taxa = ["balt1263", "indo1320"]
    units = "bp" # before present
    age = "hpd(4316, 4883, 3797)"
    notes = "Balto-Slavic–Indo-Iranian break-up: 2933–1847 bc (mean 2366 bc)"

    [inferredage.Stage2_BaltoSlavicBreakUp]
    taxa = ["balt1263"]
    units = "bp" # before present
    age = "hpd(3281, 3757, 2832)"
    notes = "Balto-Slavic break-up: 1807–882 bc (mean 1331 bc)"

    [inferredage.Stage2_IndoIranianBreakUp]
    taxa = ["indo1320"]
    units = "bp" # before present
    age = "hpd(4180, 4050, 3397)"
    notes = "Indo-Iranian break-up: 2100–1447 bc (mean 2230 bc)"

    [inferredage.Stage3_AnatolianSplit]
    taxa = ["indo1319"]
    age = "hpd(5636, 5400, 6089)"
    units = "bp" # before present
    notes = "Anatolian split-off (root): 4139–3450 bc (mean 3686 bc)"

    [inferredage.Stage3_TocharianSplit]
    taxa = ["tokh1241"]
    age = "hpd(4961, 4212, 5677)"
    units = "bp" # before present
    notes = "Tocharian split-off: 3727–2262 bc (mean 3011 bc)"

    [inferredage.Stage3_InnerIEBreakUp]
    taxa = ["clas1257"]
    age = "hpd(4667, 4112, 5307)"
    units = "bp" # before present
    notes = "Inner IE break-up: 3357–2162 bc (mean 2717 bc)"

    [inferredage.Stage3_GreekArmenianBreakUp]
    taxa = ["grae1234", "arme1241"]
    age = "hpd(3965, 3357, 4626)"
    units = "bp" # before present
    notes = "Greek-Armenian break-up: 2676–1407 bc (mean 2015 bc)"

    [inferredage.Stage3_ItalicGermanicCelticBreakUp]
    taxa = ["ital1284", "germ1287", "celt1248"]
    age = "hpd(4030, 3487, 4605)"
    units = "bp" # before present
    notes = "Italic-Germanic-Celtic break-up: 2655–1537 bc (mean 2080 bc)"

    [inferredage.Stage3_InsularCelticBreakUp]
    taxa = ["insu1254"]
    age = "hpd(2193, 1855, 2546)"
    units = "bp" # before present
    notes = "Insular Celtic break-up: 596bc–95 ad (mean 243 bc)"

    [inferredage.Stage3_BaltoSlavicIndoIranianBreakUp]
    taxa = ["balt1263", "indo1320"]
    age = "hpd(4191, 3740, 4673)"
    units = "bp" # before present
    notes = "Balto-Slavic–Indo-Iranian break-up: 2723–1790 bc (mean 2241 bc)"

    [inferredage.Stage3_BaltoSlavicBreakUp]
    taxa = ["balt1263"]
    age = "hpd(3200, 2805, 3636)"
    units = "bp" # before present
    notes = "Balto-Slavic break-up: 1686–855 bc (mean 1250 bc)"

    [inferredage.Stage3_IndoIranianBreakUp]
    taxa = ["indo1320"]
    age = "hpd(3690, 3408, 3994)"
    units = "bp" # before present
    notes = "Indo-Iranian break-up: 2044–1458 bc (mean 1740 bc)"



