
title = "Bayesian phylogenetic analysis of Semitic languages identifies an Early Bronze Age origin of Semitic in the Near East"

doi = "10.1098/rspb.2009.0408"

abstract = """
The evolution of languages provides a unique opportunity to study human population history. The origin of Semitic and the nature of dispersals by Semitic-speaking populations are of great importance to our understanding of the ancient history of the Middle East and Horn of Africa. Semitic populations are associated with the oldest written languages and urban civilizations in the region, which gave rise to some of the world's first major religious and literary traditions. In this study, we employ Bayesian computational phylogenetic techniques recently developed in evolutionary biology to analyse Semitic lexical data by modelling language evolution and explicitly testing alternative hypotheses of Semitic history. We implement a relaxed linguistic clock to date language divergences and use epigraphic evidence for the sampling dates of extinct Semitic languages to calibrate the rate of language evolution. Our statistical tests of alternative Semitic histories support an initial divergence of Akkadian from ancestral Semitic over competing hypotheses (e.g. an African origin of Semitic). We estimate an Early Bronze Age origin for Semitic approximately 5750 years ago in the Levant, and further propose that contemporary Ethiosemitic languages of Africa reflect a single introduction of early Ethiosemitic from southern Arabia approximately 2800 years ago.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Andrew Kitchen",
    "Christopher Ehret",
    "Shiferaw Assefa",
    "Connie J. Mulligan"
]

# parts of the world
groups = ["Semitic"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Kitchen2009"

# type of study
type = ['phylogenetic', 'dating']
framework = ['bayesian']

# short label of taxa "37 languages from.."
description = "25 Semitic languages"

# data
[data]
    [data.lexicon]
    ntaxa = 25
    nchars = 96
    nsites = 673
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh100'
    comment = ''

# date calibrations
[calibration]
    
    notes = ""

    [calibration.akkadian]
    taxa = ['akka1240']
    age = "2800" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = "tip calibration"

    [calibration.biblicalaramaic]
    taxa = ['impe1235']
    age = "1800" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = "tip calibration"

    [calibration.geez]
    taxa = ['geez1241']
    age = "1700" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = "tip calibration"

    [calibration.ancienthebrew]
    taxa = ['anci1244']
    age = "2600" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = "tip calibration"

    [calibration.ugaritic]
    taxa = ['ugar1238']
    age = "3400" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = "tip calibration"

    # clades
    [calibration.hebrewclade]
    taxa = ['hebr1246']
    age = "uniform(3200, 4200)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = ""

    [calibration.ugariticclade]
    taxa = ['ugar1238']
    age = "uniform(3400, 4400)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = ""

    [calibration.aramaicclade]
    taxa = ['aram1259']
    age = "uniform(2850, 3850)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = ""

    [calibration.amharicclade]
    taxa = ['amha1245']
    age = "uniform(700, 1700)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = ""

    [calibration.root]
    taxa = ['semi1276']
    age = "uniform(4350, 8000)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = ""

# analysis information
[analysis]
    [analysis.multistate]
    tool = 'beast'
    model = 'mk+gamma+relaxed'
    details = ""

    [analysis.binary]
    tool = 'beast'
    model = 'ctmc+gamma+relaxed'
    details = ""
    best = 'true'

[inferredages]
    
    notes = ""
    
    [inferredage.root]
    taxa = ['semi1276']
    age = "hpd(5750, 4400, 7400)"
    units = "ybp"
    details = "note: nested within a uniform(4350, 8000)"
    best = 'true'

    [inferredage.cent2236]
    taxa = ['cent2236']
    age = "hpd(4450, 3650, 5800)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.nort3165]
    taxa = ['nort3165']
    age = "hpd(4050, 3750, 4400)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.arab1394]
    taxa = ['arab1394']
    age = "hpd(850, 400, 1370)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.southsemitic]
    taxa = ['ethi1244', 'mode1252']
    age = "hpd(4650, 3300, 6250)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.mode1252]
    taxa = ['mode1252']
    age = "hpd(2050, 1100, 3100)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.ethi1244]
    taxa = ['ethi1244']
    age = "hpd(2850, 2000, 3800)"
    units = "ybp"
    details = ""
    best = 'true'


[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/kitchen_et_al2009" }
cldf = { title = "CLDF Dataset", link = "https://github.com/lexibank/kitchensemitic" }
links = []

