
title = "Phylogeographic analysis of the Bantu language expansion supports a rainforest route"

doi = "10.1073/pnas.2112853119"

abstract = """
The Bantu expansion transformed the linguistic, economic, and cultural composition of sub-Saharan Africa. However, the exact dates and routes taken by the ancestors of the speakers of the more than 500 current Bantu languages remain uncertain. Here, we use the recently developed “break-away” geographical diffusion model, specially designed for modeling migrations, with “augmented” geographic information, to reconstruct the Bantu language family expansion. This Bayesian phylogeographic approach with augmented geographical data provides a powerful way of linking linguistic, archaeological, and genetic data to test hypotheses about large language family expansions. We compare four hypotheses: an early major split north of the rainforest; a migration through the Sangha River Interval corridor around 2,500 BP; a coastal migration around 4,000 BP; and a migration through the rainforest before the corridor opening, at 4,000 BP. Our results produce a topology and timeline for the Bantu language family, which supports the hypothesis of an expansion through Central African tropical forests at 4,420 BP (4,040 to 5,000 95% highest posterior density interval), well before the Sangha River Interval was open.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Ezequiel Koile",
    "Simon J. Greenhill",
    "Damián E. Blasi",
    "Remco Bouckaert",
    "Russell D. Gray"
]

# parts of the world
groups = ["Bantu"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Koile2022"

# type of study
type = ['phylogenetic', 'dating', 'phylogeography']
framework = ['bayesian']

# short label of taxa "37 languages from.."
description = "636 Bantu languages"

# data
[data]
    [data.lexicon]
    ntaxa = 419
    nchars = ""
    nsites = ""
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh100'
    comment = ''

    [data.lexicon_augmented]
    ntaxa = 614
    nchars = ""
    nsites = ""
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh100'
    comment = "This posterior distribution has 419 varieties corresponding to 376 languages according to Glottolog. For each tree in the posterior, we imputed the remaining 195 languages listed in Glottolog for which we have no lexical data (see Results), by randomly inserting them in their corresponding clade"
    
    
# date calibrations
[calibrations]

    [calibration.bantoid_vs_nonbantu]
    taxa = ["bant1294"]
    age = "lognormal(4000, 0.8, 4220, realspace=True)"
    units = "ybp" # ybp
    description = "5,000 B.P. or older for Bantoid, non-Bantu (58)"

    [calibration.narrowbantu]
    taxa = ["narr1281"]
    age = "lognormal(400, 0.8, 3920, realspace=True)"
    units = "ybp" # ybp
    description = "4,000–5,000 B.P. for Narrow Bantu (13, 14, 16, 44, 59, 60);"
    
    [calibration.mbambubi]
    taxa = ["bub1242", "mbam1252"]
    age = "lognormal(200, 0.8, 2960, realspace=True)"
    units = "ybp" # ybp
    description = "3,000–3,500 B.P. for the Mbam-Bubi ancestor"

    [calibration.easternbantu]
    taxa = ["east2731"]
    age = "lognormal(10, 2.0, 2495, realspace=True)"
    units = "ybp" # ybp
    description = "2,500 B.P. for Eastern Bantu (62)"

# analysis information
[analysis]

    [analysis.tree1]
        tool = 'beast2'
        model = 'ctmc+strict'
        details = ""
    

    [analysis.tree2]
        tool = 'beast2'
        model = 'ctmc+relaxed'
        details = ""
    

    [analysis.tree3]
        tool = 'beast2'
        model = 'ctmc+gamma4+strict'
        details = ""
    

    [analysis.tree4]
        tool = 'beast2'
        model = 'ctmc+gamma4+relaxed'
        details = "best fitting model"
    

    [analysis.tree5]
        tool = 'beast2'
        model = 'covarion+strict'
        details = ""
    

    [analysis.tree6]
        tool = 'beast2'
        model = 'covarion+relaxed'
        details = ""
    

    [analysis.tree7]
        tool = 'beast2'
        model = 'covarion+gamma4+strict'
        details = ""
    

    [analysis.tree8]
        tool = 'beast2'
        model = 'covarion+gamma4+relaxed'
        details = ""
    
    [analysis.phylogeography]
        tool = 'beast2'
        model = 'ctmc+gamma4+relaxed+phylogeo(breakaway)'
        details = ""

    [analysis.phylogeography_augmented]
        tool = 'beast2'
        model = 'ctmc+gamma4+relaxed+phylogeo(breakaway)'
        details = "data:lexicon_augmented"


[inferredages]
    
    notes = ""
    
    [inferredage.root]
    taxa = ['bant1294']
    age = "hpd(4940, 4500, 5400)"
    units = "ybp"
    notes = ""
    
    [inferredage.sout3152]
    taxa = ['sout3152']
    age = "hpd(4140, 3950, 4380)"
    units = "ybp"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
links = []

