
title = "Bayesian phylogenetic analysis supports an agricultural origin of Japonic languages."

doi = "10.1098/rspb.2011.0518"

abstract = """
Languages, like genes, evolve by a process of descent with modification. This striking similarity between biological and linguistic evolution allows us to apply phylogenetic methods to explore how languages, as well as the people who speak them, are related to one another through evolutionary history. Language phylogenies constructed with lexical data have so far revealed population expansions of Austronesian, Indo-European and Bantu speakers. However, how robustly a phylogenetic approach can chart the history of language evolution and what language phylogenies reveal about human prehistory must be investigated more thoroughly on a global scale. Here we report a phylogeny of 59 Japonic languages and dialects. We used this phylogeny to estimate time depth of its root and compared it with the time suggested by an agricultural expansion scenario for Japanese origin. In agreement with the scenario, our results indicate that Japonic languages descended from a common ancestor approximately 2182 years ago. Together with archaeological and biological evidence, our results suggest that the first farmers of Japan had a profound impact on the origins of both people and languages. On a broader level, our results are consistent with a theory that agricultural expansion is the principal factor for shaping global linguistic diversity."""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Sean Lee",
    "Toshikazu Hasegawa"
]

# parts of the world
groups = ["Japonic"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Lee2011"

# type of study
type = ["phylogenetic", "dating"]
framework = ['bayesian', 'network']

# short label of taxa "37 languages from.."
description = "59 Japonic languages"

# data
[data]
    [data.lexicon]
    ntaxa = 59
    nchars = 210
    nsites = 675
    datatype = 'lexical cognates'
    source = ''
    items = 'swadesh200'
    comment = ''
    
[calibrations]

    [calibration.tokyokyoto]
    taxa = ['toky1238', 'kyot1238']
    age = "normal(407, 135.2)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = ""

    [calibration.oldjapanese]
    taxa = ['oldj1239']
    age = "unknown(1216, 1300)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = """The relaxed sample date calibrations were
    assigned to Old and Middle Japanese with lognormal priors in which their 95
    per cent of the distributions lie between the upper and the lower bounds of
    each era; 1216–1300 YBP for Old Japanese and 437-674 YBP for Middle
    Japanese."""
    
    [calibration.middlejapanese]
    taxa = ['?']  # middle japanese
    age = "unknown(437, 674)" # x, normal(x, y), uniform(x,y)
    units = "ybp" # ybp
    description = """The relaxed sample date calibrations were
    assigned to Old and Middle Japanese with lognormal priors in which their 95
    per cent of the distributions lie between the upper and the lower bounds of
    each era; 1216–1300 YBP for Old Japanese and 437-674 YBP for Middle
    Japanese."""


# analysis information
[analysis]
    [analysis.network]
        tool = 'splitstree'
        model = 'neighbornet'
        details = ""


    [analysis.tree1]
        tool = 'beast'
        model = 'ctmc+strict+gamma8'
        details = ""


    [analysis.tree2]
        tool = 'beast'
        model = 'ctmc+relaxed+gamma8'
        details = ""


    [analysis.tree3]
        tool = 'beast'
        model = 'covarion+strict'
        details = ""


    [analysis.tree4]
        tool = 'beast'
        model = 'covarion+relaxed'
        details = "best fitting model"

[inferredages]
    
    notes = ""
    
    [inferredage.tree2]
    taxa = ['japo1237']
    age = "hpd(2182, 1239, 4190)"
    units = "ybp"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/lee_and_hasegawa" }
cldf = { title = "CLDF Dataset", link = "https://github.com/lexibank/leejaponic" }
links = []
