title = "Lexicalization patterns in core vocabulary: A cross-creole study of semantic molecules"

doi = "10.1075/z.211.14lev"

abstract = """
The study of semantic domains is important for creolistics, given the complex label-meaning configuration in
creoles vis-à-vis the European lexifiers. Due to the lexical semantic creativity in the creolization process as
well as the subse- quent developments and contacts with lexifiers, substrates, and other contact varieties, each
domain seems to have its own history, its own configuration. Comparing words in four different semantic domains,
we contrast the labels and lexicalizations of social concepts, body-part terms, environmental con- cepts, and
abstract categories, with an anchor in core categories in conceptual semantics. Based on findings from
cross-linguistic investigations into core vocabularies: semantic molecules and semantic primes, we study the
lexicaliza- tions of the following meanings in creoles: ‘children’, ‘women’, ‘men’, ‘mother’, ‘father’, ‘wife’,
‘husband’ (social molecules), ‘head’, ‘eyes’, ‘ears’, ‘mouth’, ‘nose’, ‘hands’, ‘legs’ (body-part molecules),
‘sun’, ‘sky’, ‘ground, ‘water’, ‘fire’, ‘day’, ‘night’ (environmental molecules), and ‘not’, ‘maybe’, ‘can’,
‘because’, ‘if’, ‘very’ and ‘more’ (semantic primes – abstract concepts). We utilize phylogenetic net- works to
compare and contrast lexicalization patterns between domains. Our study suggests that these core
semantic-conceptual constructs tend to cluster with their lexifiers, but that there are important differences
across domains – the label-meaning configurations of the social domain stand out as the most diverse, and the
environmental domain as the most homogenous.

"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Carsten Levisen", "Karime Aragón"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Levisen_2017c"

# type of study
type = ['network']  # phylogenetic,dating,phylogeography,macroevolutionary,trait,review,tutorial

# short description of the study, one line.
description = "Network based comparisons of lexical categories."

# data
[data]

    notes = ""
    
    [data.nsm]
    ntaxa = 20
    nchars = "?"
    nsites = "?"
    datatype = 'semantic primes'
    source = ''
    items = ''
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.network1]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "Phylogenetic network for the lexicalization of abstract concepts."

    [analysis.network2]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "Phylogenetic network for lexicalizations of social molecules."

    [analysis.network3]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "Phylogenetic network for lexicalization of body-part molecules."

    [analysis.network4]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = "Phylogenetic network for environmental meanings."

