title = "Why we need a gradient approach to word order"

doi = "10.1515/ling-2021-0098"

abstract = """
This article argues for a gradient approach to word order, which treats word order preferences, both within and
across languages, as a continuous variable. Word order variability should be regarded as a basic assumption,
rather than as something exceptional. Although this approach follows naturally from the emergentist usage-based
view of language, we argue that it can be beneficial for all frameworks and linguistic domains, including
language acquisition, processing, typology, language contact, language evolution and change, and formal
approaches. Gradient approaches have been very fruitful in some domains, such as language processing, but their
potential is not fully realized yet. This may be due to practical reasons. We discuss the most pressing
methodological challenges in corpus-based and experimental research of word order and propose some practical
solutions.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Natalia Levshina", "Savithry Namboodiripad", "Marc Allassonnière-Tang", "Mathew Kramer", "Luigi Talamo", "Annemarie Verkerk", "Sasha Wilmoth", "Gabriela Garrido Rodriguez", "Timothy Michael Gupton", "Evan Kidd", "Zoey Liu", "Chiara Naccarato", "Rachel Nordlinger", "Anastasia Panova", "Natalia Stoynova"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Levshina_2023"

# type of study
type = ['trait']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['likelihood'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""


# data
[data]

    notes = ""
    
    [data.wordorder]
    ntaxa = 36
    nchars = 24
    nsites = 24
    datatype = 'structural features'
    source = ''
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.Dunn2011]
    source = '@Dunn2011'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.lambda]
    tool = 'geiger'
    model = 'lambda'
    details = ""
    data = ""
    times = 24


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []