title = "Phylogenetic reconstruction in syntax: the Parametric Comparison Method"

doi = "10.1017/9781107279070.013"

abstract = """
The Parametric Comparison Method (PCM) is a novel tool for studying the
historical evolution and classification of languages. The intuition behind it
is that purely theoretical advances of linguistics over the past few decades
may provide an innovative system for reconstructing language
phylogenies.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Giuseppe Longobardi", "Cristina Guardiano"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@LongobardiGuardiano2017"

# type of study
type = ['review']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['distance'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.parameters]
    ntaxa = 40
    nchars = 75
    nsites = 75
    datatype = 'syntactical features'
    source = ''
    items = ''
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = 'phylip'
    model = 'kitsch'
    details = ""
    data = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []