title = "Uralic typology in the light of a new comprehensive dataset"

doi = "10.1075/jul.00002.nor"

abstract = """
This paper presents the Uralic Areal Typology Online (UraTyp 1.0), a typological dataset of 35
Uralic languages and a total of 360 features, mainly covering the levels of morphology, syntax, and
phonology. The features belong to two different datasets: 195 features' definitions originate from
the Grambank (GB) database, developed for comparison of world language typology, whereas 165
features (UT) have been designed specifically to describe the typological variation within the
Uralic language family. We present a series of analyses of the dataset demonstrating its scope and
possibilities. The complete data set correctly identifies the main Uralic subgroups in a Principal
Components Analysis, whereas GB data alone is insufficiently granular to detect this
family-internal structure. Similar analyses limited to various typological subdomains also give
variable results. A model-based admixture analysis identifies four distinct areas of historical
interaction: Saami, Finnic, the Volga area and Ob-Ugric.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Miina Norvik", "Yingqi Jing", "Michael Dunn", "Robert Forkel", "Terhi Honkola", "Gerson Klumpp", "Richard Kowalik", "Helle Metslang", "Karl Pajusalu", "Minerva Piha", "Eva Saar", "Sirkka Saarinen", "Outi Vesakoski"]

# parts of the world
groups = ['Uralic']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Norvik_2022"

# type of study
type = ['structure']
framework = ['statistical']

# data
[data]

    notes = ""
    
    [data.UraTyp]
    ntaxa = 33
    nchars = 165
    nsites = 165
    datatype = 'mixed'
    source = ''
    items = ''
    comment = ''

    [data.Grambank]
    ntaxa = 29
    nchars = 195
    nsites = 195
    datatype = 'structural features'
    source = '@Grambank'
    items = ''
    comment = ''
    
# analysis information
[analysis]
    
    notes = ""
    
    [analysis.snmf]
    tool = 'LEA'
    model = 'sNMF'
    details = ""
    data = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []