
title = "A Bayesian approach to the classification of Tungusic languages"

doi = "10.1075/dia.20010.osk"

abstract = """
The Tungusic language family is comprised of languages spoken in Siberia, the Russian Far East, Northeast China and Xinjiang. There is a general consensus that these languages are genealogically related and descend from a common ancestral language. Nevertheless, there is considerable disagreement with regard to the internal structure of the Tungusic family and the time depth of its separation into daughter languages. Here we use computational Bayesian phylogenetic methods to generate a phylogeny of Tungusic languages and estimate the time-depth of the family. Our analysis is based on the recently introduced Leipzig-Jakarta-Jena list, a dataset of 254 basic vocabulary items collected for 21 Tungusic doculects. Our results are consistent with two basic classifications previously proposed in the literature, notably a Manchu-Tungusic classification, in which the break-up of Jurchenic constitutes the first split in the tree, as well as a North-South classification, which includes a Jurchenic-Nanaic and an Orochic-Ewenic branch. In addition, we obtain a time-depth for the age of Proto-Tungusic between the 8th century BC and the 12th century AD (95% highest posterior density interval). Previous classifications of Tungusic were based on both classical historical comparative linguistic and lexicostatistic approaches, but the application of Bayesian phylogenetic methods to the Tungusic languages has not so far been attempted. In contrast to previous approaches, our Bayesian analysis adds an understanding of the statistical robustness of the proposed branches and infers absolute divergence dates, allowing variation of rates of change across branches and cognate sets. In this way, our research provides a reliable quantitative basis for previous estimates based on classical historical linguistic and lexicostatistic approaches."""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Sofia Oskolskaya",
    "Ezequiel Koile",
    "Martine Robbeets"
]

# parts of the world
groups = ["Tungusic"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Oskolskaya_2021"

# type of study
type = ["phylogenetic", "dating"]

# short label of taxa "37 languages from.."
taxa = "21 Tungusic languages"

# data
[data]
    [data.lexicon]
    ntaxa = 21
    nchars = 254
    nsites = 1110
    datatype = 'lexical cognates'
    source = ''
    items = 'leipzigjakartajena'
    comment = ''

# date calibrations
[calibrations]

    [calibration.jurchen]
    taxa = ["jurc1239"]
    age = "351"
    units = "ybp" # ybp
    description = "sampled ancestor: Jurchen at 351 BP (1599 AD)"
    
    [calibration.modernjurchenic]
    taxa = ["manc1250"]
    age = "lognormal(200, 100, 330, realspace=True)"
    units = "ybp" # ybp
    description = "The first calibration point refers to the time of extinction of Jurchen and the appearance of Manchu. It is believed that the Manchu language was a direct descendent of Jurchen, a dynastic language of the Jin empire (1115–1234 AD), or some of its dialects (Janhunen 2012: 6). Known written materials in Jurchen date back to the 12th–16th centuries, while the first Manchu manuscript is dated to 1599 (Gorelova 2002: 50). This period of transition from Jurchen to Manchu texts provides a helpful reference point: Jurchen was no longer used by 1599."

    [calibration.manchuxibe]
    taxa = ["manc1251"]
    age = "lognormal(130, 40, 131, realspace=True)"
    units = "ybp" # ybp
    description = "The second calibration point concerns the same Jurchenic group. On the basis of historical evidence, we know that in 1764, the Xibe people, a Manchu tribe, resettled in the non-Manchu speaking area of Xinjiang, a province in the northwest of China (Gorelova 2002: 31). Since then, the Xibe variety became isolated from other Manchu dialects. Therefore, 1764 can serve as a reference point for the split between Manchu and Xibe."

    [calibration.siberianevenki]
    taxa = ["sibe1251"]
    age = "lognormal(120, 60, 175, realspace=True)"
    units = "ybp" # ybp
    description = "In 1723, Messerschmidt collected some vocabulary from various Evenki tribes in different regions (Messerschmidt 1964). His data show that the distinction in the realization of Proto-Evenki *s as /s/ or /ʃ/ had already taken place. Furthermore, Lindenau documented a variant /h/ in 1744–1745. The phonetic realization of *s is one of the basic features for the division into modern Northern, Eastern and Southern Evenki dialects. Although these data indicate that the distribution of Evenki dialects was different in the 18th century, they also show that the break-up into at least two dialectal groups with different realization of *s had already taken place (Vasilevich 1969; Mishchenkova 2019). We used 1723 as our third calibration point, indicating an upper ceiling for the break-up of Siberian Evenki: Chiringda, Stony Tunguska, Strelka-Chunya, Teteya and Tutonchany Evenki varieties."

    [calibration.earlyjurchensplit]
    taxa = ["manc1250", "east2366"]
    age = "normal(2100, 275)"
    units = "ybp" # ybp
    description = "...we decided to test an additional calibration point, which is hypothetical in its nature. By the end of the 3rd century AD, the Primorye region (currently the southern part of the Russian Far East, including administrative regions Primorskij kraj and a part of Khabarovskij kraj with the northern border along the Amur river) went through a period of sharp climate cooling which caused the migration of the local tribes and the reversion from millet farming to hunting and fishing (Yanushevich et al. 1990; Robbeets et al. 2020). Jurchenic speakers living in the current area of Northeastern China were predominantly farmers, while other Tungusic populations who lived predominantly in the current regions of Russia were hunters, fishers and gatherers. Therefore, we hypothesize that the climate cooling in the 3rd century can be associated with the separation of Jurchenic from other Tungusic languages: non-Jurchenic tribes might have lived in the Primorye region by the end of 3rd century AD and they might have had to change their subsistence methods because of climate cooling. Since the last calibration point is uncertain, we performed two parallel analyses: one with the three documented calibration points, and another including this fourth hypothetical one."

# analysis information
[analysis]

    [analysis.tree1]
        tool = 'beast2'
        model = 'sa+fbd+ctmc+strict+gamma1'
        details = ""


    [analysis.tree2]
        tool = 'beast2'
        model = 'sa+fbd+ctmc+strict+gamma4'
        details = ""


    [analysis.tree3]
        tool = 'beast2'
        model = 'sa+fbd+ctmc+relaxed+gamma1'
        details = ""


    [analysis.tree4]
        tool = 'beast2'
        model = 'sa+fbd+ctmc+relaxed+gamma4'
        details = ""


    [analysis.tree5]
        tool = 'beast2'
        model = 'sa+fbd+covarion+strict+gamma1'
        details = ""


    [analysis.tree6]
        tool = 'beast2'
        model = 'sa+fbd+covarion+strict+gamma4'
        details = ""


    [analysis.tree7]
        tool = 'beast2'
        model = 'sa+fbd+covarion+relaxed+gamma1'
        details = "best fitting model"


    [analysis.tree8]
        tool = 'beast2'
        model = 'sa+fbd+covarion+relaxed+gamma4'
        details = ""


    [analysis.tree9]
        tool = 'beast2'
        model = 'sa+fbd+stochasticdollo+strict+gamma1'
        details = ""


    [analysis.tree10]
        tool = 'beast2'
        model = 'sa+fbd+stochasticdollo+strict+gamma4'
        details = ""


    [analysis.tree11]
        tool = 'beast2'
        model = 'sa+fbd+stochasticdollo+relaxed+gamma1'
        details = ""


    [analysis.tree12]
        tool = 'beast2'
        model = 'sa+fbd+stochasticdollo+relaxed+gamma4'
        details = ""


    [analysis.tree13]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollo+strict+gamma1'
        details = ""


    [analysis.tree14]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollo+strict+gamma4'
        details = ""


    [analysis.tree15]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollo+relaxed+gamma1'
        details = ""


    [analysis.tree16]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollo+relaxed+gamma4'
        details = ""


    [analysis.tree17]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollocovarion+strict+gamma1'
        details = ""


    [analysis.tree18]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollocovarion+strict+gamma4'
        details = ""


    [analysis.tree19]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollocovarion+relaxed+gamma1'
        details = ""


    [analysis.tree20]
        tool = 'beast2'
        model = 'sa+fbd+pseudodollocovarion+relaxed+gamma4'
        details = ""


[inferredages]
    
    notes = ""
    
    [inferredage.withoutearlyjurchensplit]
    taxa = ['tung1282']
    age = "hpd(1487, 796, 2687)"
    units = "ybp"
    notes = "best fitting model"

    [inferredage.withearlyjurchensplit]
    taxa = ['tung1282']
    age = "hpd(2041, 1272, 3153)"
    units = "ybp"
    notes = ""

[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/oskolskaya_et_al2021" }
cldf = { title = "CLDF Dataset", link = "https://github.com/lexibank/oskolskayatungusic" }
links = []
