title = "Maximum likelihood models for glottochronology and for reconstructing linguistic phylogenies"

doi = ""

abstract = """
I shall discuss in this chapter how maximum likelihood statistical models of 
linguistic evolution can be used to infer phylogenies of languages, and to
derive quantitative estimates of rates at which individual words evolve. A phylogenetic
tree of seven Indo-European languages is reconstructed using a novel maximum likelihood
model. The tree seems to capture several important features of the relationship
amongst these languages.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ['Mark Pagel']

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@pagel2000b"

# type of study
type = ['phylogenetic', 'methodological']
framework = ['likelihood']
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.kruskal1971]
    ntaxa = 7
    nchars = 18
    nsites = 18
    datatype = 'lexical cognates'
    source = '@Kruskal1971'
    items = ''
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = 'custom'
    model = ''
    details = ""
    data = ""
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []