title = "Ultraconserved words point to deep language ancestry across Eurasia"

doi = "10.1073/pnas.1218726110"

abstract = """The search for ever deeper relationships abstract the World's languages is bedeviled by
the fact that most words evolve too rapidly to preserve evidence of their ancestry beyond 5,000 to
9,000 y. On the other hand, quantitative modeling indicates that some "ultraconserved" words exist
that might be used to find evidence for deep linguistic relationships beyond that time barrier. Here
we use a statistical model, which takes into account the frequency with which words are used in
common everyday speech, to predict the existence of a set of such highly conserved words among seven
language families of Eurasia postulated to form a linguistic superfamily that evolved from a common
ancestor around 15,000 y ago. We derive a dated phylogenetic tree of this proposed superfamily with a
time-depth of ∼14,450 y, implying that some frequently used words have been retained in related forms
since the end of the last ice age. Words used more than once per 1,000 in everyday speech were 7 to
10-times more likely to show deep ancestry on this tree. Our results suggest a remarkable fidelity in
the transmission of some words and give theoretical justification to the search for features of
language that might be preserved across wide spans of time and geography. """

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Mark Pagel", "Quentin D. Atkinson", "Andreea S. Calude", "Andrew Meade"]

# parts of the world
groups = [
    'Altaic',
    'Turkic', 'Mongolic', 'Tungusic', 'Koreanic', 'Japonic',
    'Chukchee-Kamchatkan',
    'Dravidian',
    'Inuit-Yupik',
    'Indo-European',
    'Kartvelian',
    'Uralic'
]

# bibkey citation in sources.bib
bibkey = "@Pagel_2013"

# type of study
type = ['phylogenetic', 'dating']
framework = ['bayesian']

# short description of the study, one line.
description = "Attempt to identify the deeper relationships between language families in Eurasia"

# data
[data]

    notes = """
    We recorded the reconstructed proto-
    words as proposed in the LWED for each of the 200 meanings in
    the Swadesh fundamental vocabulary for the seven language
    families. We excluded 12 meanings from the list of 200 for which
    the LWED provided reconstructions for only one or at most two
    language families.
    """
    
    [data.lwed]
    ntaxa = 7
    nchars = 188
    nsites = 3804
    datatype = 'lexical cognates'
    source = '@LWED'
    items = 'swadesh200'
    comment = ''


# date calibrations
[calibrations]

    notes = ""

    [calibration.pie]
    taxa = ['indo1319']
    age = "normal(8700, 544)" # x, normal(x, y), uniform(x,y), lognormal(x, y, z, realspace=True)
    units = "ybp" # ybp
    description = "from @GrayAtkinson2003"

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = 'unknown'
    model = '?'
    details = ""
    data = ""

    [analysis.chukchikamchatkan]
    tool = 'unknown'
    model = '?'
    details = ""
    data = ""

[inferredages]
    
    notes = ""
    
    [inferredage.protochukchikamchatkan]
    taxa = ['chuk1271']
    age = "normal(692, 67)"
    units = "y2000"
    notes = "n.b. not really used as time inference, just a scalar for the rest of the tree"

    [inferredage.root_1]
    taxa = [
        'mong1349', # Mongolic
        'tung1282', # Tungusic
        'kore1284', # Koreanic
        'japo1237', # Japonic
        'chuk1271', # Chukchee-Kamchatkan
        'drav1251', # Dravidian
        'eski1264', # Inuit-Yupik
        'indo1319', # Indo-European
        'kart1248', # Kartvelian
        'ural1272', # Uralic
    ]
    age = "hpd(14450, 11720, 18380)"
    units = "y2000"
    notes = "rooting 1 (on branch to proto-Dravidian)"

    [inferredage.root_2]
    taxa = [
        'mong1349', # Mongolic
        'tung1282', # Tungusic
        'kore1284', # Koreanic
        'japo1237', # Japonic
        'chuk1271', # Chukchee-Kamchatkan
        'drav1251', # Dravidian
        'eski1264', # Inuit-Yupik
        'indo1319', # Indo-European
        'kart1248', # Kartvelian
        'ural1272', # Uralic
    ]
    age = "hpd(15610, 11720, 20400)"
    units = "y2000"
    notes = "rooting 2 (on branch to proto-Kartvelian)"



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []