title = "Kinbank: A global database of kinship terminology"

doi = "10.1371/journal.pone.0283218"

abstract = """
For a single species, human kinship organization is both remarkably diverse and
strikingly organized. Kinship terminology is the structured vocabulary used to classify, refer to,
and address relatives and family. Diversity in kinship terminology has been analyzed by 
anthropologists for over 150 years, although recurrent patterning across cultures remains 
incompletely explained. Despite the wealth of kinship data in the anthropological record, comparative studies
of kinship terminology are hindered by data accessibility. Here we present Kinbank, a new database of
210,903 kinterms from a global sample of 1,229 spoken languages. Using open-access and transparent
data provenance, Kinbank offers an extensible resource for kinship terminology, enabling researchers
to explore the rich diversity of human family organization and to test longstanding hypotheses about
the origins and drivers of recurrent patterns. We illustrate our contribution with two examples. We
demonstrate strong gender bias in the phonological structure of parent terms across 1,022 languages,
and we show that there is no evidence for a coevolutionary relationship between cross-cousin mar-
riage and bifurcate-merging terminology in Bantu languages. Analysing kinship data is """

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    
    "Sam Passmore", "Wolfgang Barth", "Simon J. Greenhill", "Kyla Quinn", "Catherine Sheard",
    "Paraskevi Argyriou", "Joshua Birchall", "Claire Bowern", "Jasmine Calladine", "Angarika Deb",
    "Anouk Diederen", "Niklas P. Metsäranta", "Luis Henrique Araujo", "Rhiannon Schembri", 
    "Jo Hickey-Hall", "Terhi Honkola", "Alice Mitchell", "Lucy Poole", "Péter M. Rácz", 
    "Sean G. Roberts", "Robert M. Ross", "Ewan Thomas-Colquhoun", "Nicholas Evans", "Fiona M. Jordan"

]

# parts of the world
groups = ['global']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Passmore_2023"

# type of study
type = ['trait']
framework = ['bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = "Presentation of the Kinbank database with some illustrative analyses"

# data
[data]

    notes = ""
    
    [data.kinbank_mother_father]
    ntaxa = 1022
    nchars = 2
    nsites = 2
    datatype = 'phonetic traits'
    source = '@Passmore_2023'
    items = ''
    comment = ''

    [data.kinbank_crossness]
    ntaxa = 56
    nchars = 1
    nsites = 1
    datatype = 'structural features'
    source = '@Passmore_2023'
    items = ''
    comment = ''
    
    [data.ea]
    ntaxa = 56
    nchars = 1
    nsites = 1
    datatype = 'ethnographic features'
    source = '@DPLACE;@EthAtlas'
    items = ''
    comment = 'EA023 Cousin Marriage'
    
    
# published phylogenies
[phylogenies]
    [phylogenies.jaeger2018]
    source = '@Jaeger2018'
    comment = ''

    [phylogenies.grollemund]
    source = '@Grollemund2015'
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.mother_vs_father]
    tool = 'brms'
    model = 'phylogenetic regression'
    details = ""
    data = "@phylogenies.jaeger2018; @data.kinbank_mother_father"

    [analysis.crossness_d]
    tool = 'bayestraits'
    model = 'dependent'
    details = ""
    data = "@phylogenies.grollemund; @data.ea; @data.kinbank_crossness"

    [analysis.crossness_i]
    tool = 'bayestraits'
    model = 'independent'
    details = ""
    data = "@phylogenies.grollemund; @data.ea; @data.kinbank_crossness"


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []