title = "Three tree priors and five datasets: A study of Indo-European phylogenetics"

doi = "10.1163/22105832-00802005"

abstract = """
The age of the root of the Indo-European language family has received much attention since the
application of Bayesian phylogenetic methods by Gray and Atkinson (2003). With the application of
new models, the root age of the Indo-European family has tended to decrease from an age that
supported the Anatolian origin hypothesis to an age that supports the Steppe origin hypothesis
(Chang et al., 2015). However, none of the published work in Indo-European phylogenetics has
studied the effect of tree priors on phylogenetic analyses of the Indo-European family. In this
paper, I intend to fill this gap by exploring the effect of tree priors on different aspects of the
Indo-European family's phylogenetic inference. I apply three tree priors—Uniform, Fossilized
Birth-Death (FBD), and Coalescent—to five publicly available datasets of the Indo-European language
family. I evaluate the posterior distribution of the trees from the Bayesian analysis using Bayes
Factor, and find that there is support for the Steppe origin hypothesis in the case of two tree
priors. I report the median and 95 % highest posterior density (HPD) interval of the root ages for
all three tree priors. A model comparison suggests that either the Uniform prior or the FBD prior
is more suitable than the Coalescent prior to the datasets belonging to the Indo-European language
family.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Taraka Rama"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Rama_2018"

# type of study
type = ['methodological', 'phylogenetic']
framework = ['bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other

# data
[data]

    notes = ""
    
    [data.Chang_B1]
    ntaxa = 103
    nchars = 207
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Bouckaert2012;@Chang2015'
    items = ''
    comment = ''

    [data.Chang_B2]
    ntaxa = 97
    nchars = 207
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Bouckaert2012;@Chang2015'
    items = ''
    comment = ''

    [data.Chang_Broad]
    ntaxa = 94
    nchars = 197
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Bouckaert2012;@Chang2015'
    items = ''
    comment = ''

    [data.Chang_Medium]
    ntaxa = 82
    nchars = 143
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Bouckaert2012;@Chang2015'
    items = ''
    comment = ''

    [data.Chang_Narrow]
    ntaxa = 52
    nchars = 143
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@Bouckaert2012;@Chang2015'
    items = ''
    comment = ''

# date calibrations
[calibrations]

    notes = ""

    [calibration.Hittite]
        taxa = ['hitt1242']
        age = "uniform(3500, 3600)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldHighGerman]
        taxa = ['oldh1241']
        age = "uniform(1000, 1100)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldIrish]
        taxa = ['oldi1245']
        age = "uniform(1100, 1300)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.TocharianA]
        taxa = ['tokh1242']
        age = "uniform(1200, 1500)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.TocharianB]
        taxa = ['tokh1243']
        age = "uniform(1200, 1500)"
        units = "ybp" # ybp
        description = ""

    [calibration.ClassicalArmenian]
        taxa = ['clas1249']
        age = "uniform(1300, 1600)"
        units = "ybp" # ybp
        description = ""
    
    
    [calibration.AncientGreek]
        taxa = ['anci1242']
        age = "uniform(2400, 2500)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Lycian]
        taxa = ['mily1238']
        age = "uniform(2350, 2450)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Luvian]
        taxa = ['hier1240']
        age = "uniform(3275, 3425)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldPrussian]
        taxa = ['prus1238']
        age = "uniform(500, 600)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.VedicSanskrit]
        taxa = ['sans1269']
        age = "uniform(3000, 3500)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Umbrian]
        taxa = ['umbr1253']
        age = "uniform(2100, 2300)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldEnglish]
        taxa = ['olde1238']
        age = "uniform(950, 1050)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Avestan]
        taxa = ['aves1237']
        age = "uniform(2450, 2550)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldPersian]
        taxa = ['oldp1254']
        age = "uniform(2375, 2525)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Gothic]
        taxa = ['goth1244']
        age = "uniform(1625, 1675)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Latin]
        taxa = ['lati1261']
        age = "uniform(2100, 2200)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldNorse]
        taxa = ['oldn1244']
        age = "uniform(750, 850)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Oscan]
        taxa = ['osca1245']
        age = "uniform(2100, 2300)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.OldChurchSlavonic]
        taxa = ['chur1257']
        age = "uniform(950, 1050)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Cornish]
        taxa = ['corn1251']
        age = "uniform(300, 400)"
        units = "ybp" # ybp
        description = ""
    
    [calibration.Sogdian]
        taxa = ['sogd1245']
        age = "uniform(1200, 1400)"
        units = "ybp" # ybp
        description = ""
    


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.mrbayes_FBD_B1]
        tool = 'mrbayes'
        model = 'gtr+gamma+FBD'
        details = ""
        data = "@data.Chang_B1"
        
    [analysis.mrbayes_FBD_B2]
        tool = 'mrbayes'
        model = 'gtr+gamma+FBD'
        details = ""
        data = "@data.Chang_B2"
        
    [analysis.mrbayes_FBD_Broad]
        tool = 'mrbayes'
        model = 'gtr+gamma+FBD'
        details = ""
        data = "@data.Chang_Broad"
        
    [analysis.mrbayes_FBD_Medium]
        tool = 'mrbayes'
        model = 'gtr+gamma+FBD'
        details = ""
        data = "@data.Chang_Medium"
        
    [analysis.mrbayes_FBD_Narrow]
        tool = 'mrbayes'
        model = 'gtr+gamma+FBD'
        details = ""
        data = "@data.Chang_Narrow"
        
    [analysis.mrbayes_Coalescent_B1]
        tool = 'mrbayes'
        model = 'gtr+gamma+Coalescent'
        details = ""
        data = "@data.Chang_B1"
        
    [analysis.mrbayes_Coalescent_B2]
        tool = 'mrbayes'
        model = 'gtr+gamma+Coalescent'
        details = ""
        data = "@data.Chang_B2"
        
    [analysis.mrbayes_Coalescent_Broad]
        tool = 'mrbayes'
        model = 'gtr+gamma+Coalescent'
        details = ""
        data = "@data.Chang_Broad"
        
    [analysis.mrbayes_Coalescent_Medium]
        tool = 'mrbayes'
        model = 'gtr+gamma+Coalescent'
        details = ""
        data = "@data.Chang_Medium"
        
    [analysis.mrbayes_Coalescent_Narrow]
        tool = 'mrbayes'
        model = 'gtr+gamma+Coalescent'
        details = ""
        data = "@data.Chang_Narrow"
        
    [analysis.mrbayes_Uniform_B1]
        tool = 'mrbayes'
        model = 'gtr+gamma+Uniform'
        details = ""
        data = "@data.Chang_B1"
        
    [analysis.mrbayes_Uniform_B2]
        tool = 'mrbayes'
        model = 'gtr+gamma+Uniform'
        details = ""
        data = "@data.Chang_B2"
        
    [analysis.mrbayes_Uniform_Broad]
        tool = 'mrbayes'
        model = 'gtr+gamma+Uniform'
        details = ""
        data = "@data.Chang_Broad"
        
    [analysis.mrbayes_Uniform_Medium]
        tool = 'mrbayes'
        model = 'gtr+gamma+Uniform'
        details = ""
        data = "@data.Chang_Medium"
        
    [analysis.mrbayes_Uniform_Narrow]
        tool = 'mrbayes'
        model = 'gtr+gamma+Uniform'
        details = ""
        data = "@data.Chang_Narrow"
        

[inferredages]
    
    notes = ""
    
    [inferredage.mrbayes_FBD_B1]
        taxa = ["indo1319"]
        age = "hpd(7512, 6244, 8766)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_FBD_B2]
        taxa = ["indo1319"]
        age = "hpd(7177, 6150, 8430)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_FBD_Broad]
        taxa = ["indo1319"]
        age = "hpd(6551, 5591, 7585)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_FBD_Medium]
        taxa = ["indo1319"]
        age = "hpd(6845, 5942, 7921)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_FBD_Narrow]
        taxa = ["indo1319"]
        age = "hpd(6826, 5790, 7984)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Coalescent_B1]
        taxa = ["indo1319"]
        age = "hpd(9821, 8370, 11695)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Coalescent_B2]
        taxa = ["indo1319"]
        age = "hpd(9133, 7590, 10913)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Coalescent_Broad]
        taxa = ["indo1319"]
        age = "hpd(7984, 6654, 9327)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Coalescent_Medium]
        taxa = ["indo1319"]
        age = "hpd(8345, 7070, 9818)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Coalescent_Narrow]
        taxa = ["indo1319"]
        age = "hpd(8228, 6826, 9791)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1]
        taxa = ["indo1319"]
        age = "hpd(6789, 5760, 8115)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2]
        taxa = ["indo1319"]
        age = "hpd(6738, 5536, 7986)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad]
        taxa = ["indo1319"]
        age = "hpd(5935, 5073, 6947)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium]
        taxa = ["indo1319"]
        age = "hpd(6339, 5395, 7392)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Narrow]
        taxa = ["indo1319"]
        age = "hpd(6462, 5423, 7646)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_Germanic]
        taxa = ["germ1287"]
        age = "hpd(2876, 2286, 3572)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_Germanic]
        taxa = ["germ1287"]
        age = "hpd(2816, 2256, 3458)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_Germanic]
        taxa = ["germ1287"]
        age = "hpd(2615, 2147, 3166)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_Germanic]
        taxa = ["germ1287"]
        age = "hpd(2449, 2031, 2935)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Narrow_Germanic]
        taxa = ["germ1287"]
        age = "hpd(2334, 1943, 2807)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_Romance]
        taxa = ["roma1334"]
        age = "hpd(2987, 2400, 3629)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_Romance]
        taxa = ["roma1334"]
        age = "hpd(2149, 1628, 2714)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_Romance]
        taxa = ["roma1334"]
        age = "hpd(1980, 1515, 2493)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_Romance]
        taxa = ["roma1334"]
        age = "hpd(1841, 1401, 2345)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Narrow_Romance]
        taxa = ["roma1334"]
        age = "hpd(1736, 1309, 2248)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_Scandinavian]
        taxa = ["nort3160"]
        age = "hpd(1523, 1127, 2016)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_Scandinavian]
        taxa = ["nort3160"]
        age = "hpd(1469, 1102, 1906)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_Scandinavian]
        taxa = ["nort3160"]
        age = "hpd(1340, 1024, 1697)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_Scandinavian]
        taxa = ["nort3160"]
        age = "hpd(1164, 898, 1477)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_Slavic]
        taxa = ["slav1255"]
        age = "hpd(1860, 1401, 2423)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_Slavic]
        taxa = ["slav1255"]
        age = "hpd(1822, 1378, 2309)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_Slavic]
        taxa = ["slav1255"]
        age = "hpd(1647, 1301, 2069)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_Slavic]
        taxa = ["slav1255"]
        age = "hpd(1575, 1226, 1972)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_EastBaltic]
        taxa = ["east2280"]
        age = "hpd(1584, 914, 2356)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_EastBaltic]
        taxa = ["east2280"]
        age = "hpd(1561, 936, 2265)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_EastBaltic]
        taxa = ["east2280"]
        age = "hpd(1465, 891, 2086)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_EastBaltic]
        taxa = ["east2280"]
        age = "hpd(1460, 892, 2115)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_BritishCeltic]
        taxa = ["celt1248"]
        age = "hpd(1732, 1105, 2402)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_BritishCeltic]
        taxa = ["celt1248"]
        age = "hpd(1687, 1137, 2343)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_BritishCeltic]
        taxa = ["celt1248"]
        age = "hpd(1537, 1024, 2093)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_BritishCeltic]
        taxa = ["celt1248"]
        age = "hpd(1450, 955, 2011)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_ModernIrishScotsGaelic]
        taxa = ["mode1265"]
        age = "hpd(1058, 530, 1615)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_ModernIrishScotsGaelic]
        taxa = ["mode1265"]
        age = "hpd(1052, 589, 1620)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_ModernIrishScotsGaelic]
        taxa = ["mode1265"]
        age = "hpd(967, 523, 1442)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_ModernIrishScotsGaelic]
        taxa = ["mode1265"]
        age = "hpd(834, 451, 1260)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Narrow_ModernIrishScotsGaelic]
        taxa = ["mode1265"]
        age = "hpd(829, 442, 1290)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B1_Persian-Tajik]
        taxa = ["fars1255"]
        age = "hpd(882, 424, 1412)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_B2_Persian-Tajik]
        taxa = ["fars1255"]
        age = "hpd(842, 386, 1360)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Broad_Persian-Tajik]
        taxa = ["fars1255"]
        age = "hpd(819, 409, 1250)"
        units = "ybp" # ybp
        notes = ""
    
    [inferredage.mrbayes_Uniform_Medium_Persian-Tajik]
        taxa = ["fars1255"]
        age = "hpd(704, 336, 1098)"
        units = "ybp" # ybp
        notes = ""
    
    


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []