
title = "Indo-European and Computational Cladistics"

doi = "10.1111/1467-968X.00091"

abstract = """
This paper reports the results of an attempt to recover the first-order subgrouping of the Indo-European
family using a new computational method devised by the authors and based on a ‘perfect phylogeny’
algorithm. The methodology is also briefly described, and points of theory and methodology are addressed in
connection with the experiment whose results are here reported.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Donald A. Ringe",
    "Tandy Warnow",
    "Ann Taylor",
]

# parts of the world
groups = ["Indo-European"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Ringe2002"

# type of study
type = ["phylogenetic"]
framework = ['parsimony']

# short label of taxa "37 languages from.."
description = "24 Indo-European languages"

# data
[data]
    [data.phonology]
    ntaxa = 24
    nchars = 22
    nsites = 22
    datatype = 'phonetic traits'
    source = ''
    items = ''
    comment = 'Currently our database includes 370 characters, namely 22 phonological characters, 15 morphological characters, and 333 lexical characters.'

    [data.morphological]
    ntaxa = 24
    nchars = 15
    nsites = 15
    datatype = 'morphological traits'
    source = ''
    items = ''
    comment = 'Currently our database includes 370 characters, namely 22 phonological characters, 15 morphological characters, and 333 lexical characters.'

    [data.lexical]
    ntaxa = 24
    nchars = 333
    nsites = 333
    datatype = 'lexical cognates'
    source = ''
    items = ''
    comment = 'Currently our database includes 370 characters, namely 22 phonological characters, 15 morphological characters, and 333 lexical characters.'
    
    [data.combined]
    ntaxa = 24
    nchars = 370
    nsites = 370
    datatype = 'mixed'
    source = ''
    items = ''
    comment = 'Currently our database includes 370 characters, namely 22 phonological characters, 15 morphological characters, and 333 lexical characters.'


# analysis information
[analysis]
    [analysis.tree]
    tool = 'unknown'
    model = 'perfect phylogeny'
    details = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
links = []
