
title = "Triangulation supports agricultural spread of the Transeurasian languages"

doi = "10.1038/s41586-021-04108-8"

abstract = """
The origin and early dispersal of speakers of Transeurasian languages—that is, Japanese, Korean, Tungusic, Mongolic and Turkic—is among the most disputed issues of Eurasian population history. A key problem is the relationship between linguistic dispersals, agricultural expansions and population movements. Here we address this question by 'triangulating' genetics, archaeology and linguistics in a unified perspective. We report wide-ranging datasets from these disciplines, including a comprehensive Transeurasian agropastoral and basic vocabulary; an archaeological database of 255 Neolithic–Bronze Age sites from Northeast Asia; and a collection of ancient genomes from Korea, the Ryukyu islands and early cereal farmers in Japan, complementing previously published genomes from East Asia. Challenging the traditional 'pastoralist hypothesis', we show that the common ancestry and primary dispersals of Transeurasian languages can be traced back to the first farmers moving across Northeast Asia from the Early Neolithic onwards, but that this shared heritage has been masked by extensive cultural interaction since the Bronze Age. As well as marking considerable progress in the three individual disciplines, by combining their converging evidence we show that the early spread of Transeurasian speakers was driven by agriculture.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Martine Robbeets",
    "Remco Bouckaert",
    "Matthew Conte",
    "Alexander Savelyev",
    "Tao Li",
    "Deog-Im An",
    "Ken-ichi Shinoda",
    "Yinqiu Cui",
    "Takamune Kawashima",
    "Geonyoung Kim",
    "Junzo Uchiyama",
    "Joanna Dolińska",
    "Sofia Oskolskaya",
    "Ken-Yōjiro Yamano",
    "Noriko Seguchi",
    "Hirotaka Tomita",
    "Hiroto Takamiya",
    "Hideaki Kanzawa-Kiriyama",
    "Hiroki Oota",
    "Hajime Ishida",
    "Ryosuke Kimura",
    "Takehiro Sato",
    "Jae-Hyun Kim",
    "Bingcong Deng",
    "Rasmus Björn",
    "Seongha Rhee",
    "Kyou-Dong Ahn",
    "Ilya Gruntov",
    "Olga Mazo",
    "John R. Bentley",
    "Ricardo Fernandes",
    "Patrick Roberts",
    "Ilona R. Bausch",
    "Linda Gilaizeau",
    "Minoru Yoneda",
    "Mitsugu Kugai",
    "Raffaela A. Bianco",
    "Fan Zhang",
    "Marie Himmel",
    "Mark J. Hudson",
    "Chao Ning"
]

# parts of the world
groups = [

    'Transeurasian', 'Turkic', 'Mongolic', 'Tungusic', 'Koreanic', 'Japonic',


]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Robbeets2021"

# type of study
type = ["phylogenetic", "phylogeography", "dating"]
framework = ['bayesian']

# short label of taxa "37 languages from.."
description = "98 Transeurasian languages"

# data
[data]
    [data.lexicon]
    ntaxa = 98
    nchars = 254
    nsites = 3193
    datatype = 'lexical cognates'
    source = ''
    items = ''
    comment = '3,193 cognate sets that represent 254 basic vocabulary concepts for 98 Transeurasian languages'

    [data.cultural]
    ntaxa = 255
    nchars = 172
    nsites = 172
    datatype = 'archaeological'
    source = ''
    items = ''
    comment = 'Extracting data from the published literature, we scored 172 archaeological features for 255 Neolithic and Bronze Age sites (Supplementary Data 6, Fig. 2a) and compiled an inventory of 269 directly carbon-14-dated early crop remains (Supplementary Data 9) in northern China, the Primorye, Korea and Japan.'


# analysis information
[analysis]
    [analysis.tree_lexicon_1]
        tool = 'beast2'
        model = 'covarion+strict+fbd'
        details = ""
        data = "@data.lexicon"

    [analysis.tree_lexicon_2]
        tool = 'beast2'
        model = 'covarion+relaxed+fbd'
        details = ""
        data = "@data.lexicon"


    [analysis.tree_lexicon_3]
        tool = 'beast2'
        model = 'ctmc+strict+fbd'
        details = ""
        data = "@data.lexicon"


    [analysis.tree_lexicon_4]
        tool = 'beast2'
        model = 'ctmc+relaxed+fbd'
        details = ""
        data = "@data.lexicon"


    [analysis.tree_lexicon_5]
        tool = 'beast2'
        model = 'pdcov+strict+fbd'
        details = ""
        data = "@data.lexicon"

    [analysis.tree_lexicon_6]
        tool = 'beast2'
        model = 'pdcov+relaxed+fbd'
        details = "best fitting model"
        data = "@data.lexicon"
        best = 'true'

    [analysis.tree_phylogeography]
        tool = 'beast2'
        model = 'phylogeography+relaxed'
        details = "no data beyond geographic points and tree from main analysis"

        
    [analysis.tree_culture_1]
        tool = 'beast2'
        model = 'covarion+strict+bsp'
        details = ""
        data = "@data.culture"

    [analysis.tree_culture_2]
        tool = 'beast2'
        model = 'covarion+relaxed+bsp'
        details = ""
        data = "@data.culture"


    [analysis.tree_culture_3]
        tool = 'beast2'
        model = 'ctmc+strict+bsp'
        details = ""
        data = "@data.culture"


    [analysis.tree_culture_4]
        tool = 'beast2'
        model = 'ctmc+relaxed+bsp'
        details = ""
        data = "@data.culture"


    [analysis.tree_culture_5]
        tool = 'beast2'
        model = 'pdcov+strict+bsp'
        details = ""
        data = "@data.culture"


    [analysis.tree_culture_6]
        tool = 'beast2'
        model = 'pdcov+relaxed+bsp'
        details = "best fitting model"
        data = "@data.culture"
        best = 'true'

[calibrations]
    [calibration.japonic]
    taxa = ["japo1237"]
    age = "normal(2100, 175)"
    units = "ybp"
    description = ""

    [calibration.koreanic]
    taxa = ["kore1284"]
    age = "normal(800, 175)"
    units = "ybp"
    description = ""

    [calibration.turkic]
    taxa = ["turk1311"]
    age = "normal(2100, 175)"
    units = "ybp"
    description = ""

    [calibration.mongolic]
    taxa = ["mong1349"]
    age = "normal(750, 50)"
    units = "ybp"
    description = ""

    [calibration.tungusic]
    taxa = ["tung1282"]
    age = "normal(1900, 275)"
    units = "ybp"
    description = ""


[inferredages]
    
    notes = ""
    
    [inferredage.transeurasian]
    taxa = ['japo1237', 'kore1284', 'turk1311', 'mong1349', 'tung1282',]
    age = "hpd(9181, 5595, 12793)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.altaic]
    taxa = ['turk1311', 'mong1349', 'tung1282']
    age = "hpd(6811, 4404, 10166)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.MT]
    taxa = ['mong1349', 'tung1282']  # mongolic, tungusic
    age = "hpd(4491, 2599, 6373)"
    units = "ybp"
    details = ""
    best = 'true'

    [inferredage.JK]
    taxa = ['japo1237', 'kore1284']
    age = "hpd(5458, 3335, 8024)"
    units = "ybp"
    details = ""
    best = 'true'



[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
links = []
