
title = "Internal Classification of the Alor-Pantar Language Family Using Computational Methods Applied to the Lexicon"

doi = "10.1163/22105832-20120201"

abstract = """
The non-Austronesian languages of Alor and Pantar in eastern Indonesia have been shown to be genetically related using the comparative method, but the identified phonological innovations are typologically common and do not delineate neat subgroups. We apply computational methods to recently collected lexical data and are able to identify subgroups based on the lexicon. Crucially, the lexical data are coded for cognacy based on identified phonological innovations. Tis methodology can succeed even where phonological innovations themselves fail to identify subgroups, showing that computational methods using lexical data can be a powerful tool supplementing the comparative method.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Laura C. Robinson",
    "Gary Holton"
]

# parts of the world
groups = ["Timor-Alor-Pantar"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Robinson_2012"

# type of study
type = ["phylogenetic", "delta"]
framework = ['bayesian', 'network']

# short label of taxa "37 languages from.."
description = "13 Timor-Alor-Pantar languages"

# data
[data]
    [data.lexicon]
    ntaxa = 13
    nchars = 351
    nsites = 4563
    datatype = 'lexical cognates'
    source = ''
    items = ''
    comment = ''
    

# analysis information
[analysis]
    [analysis.beast2]
    tool = 'beast2'
    model = 'stochastic dollo'
    details = ""

    [analysis.mrbayes]
    tool = 'mrbayes'
    model = '?'
    details = ""
    
    [analysis.neighbornet]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""

    [analysis.delta]
    tool = 'splitstree'
    model = 'delta'
    details = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
links = []
