title = "Evolution and Trade-Off Dynamics of Functional Load"

doi = "10.3390/e24040507"

abstract = """
Functional load (FL) quantifies the contributions by phonological contrasts to distinctions made across the
lexicon. Previous research has linked particularly low values of FL to sound change. Here, we broaden the scope of
enquiry into FL to its evolution at higher values also. We apply phylogenetic methods to examine the diachronic
evolution of FL across 90 languages of the Pama–Nyungan (PN) family of Australia. We find a high degree of
phylogenetic signal in FL, indicating that FL values covary closely with genealogical structure across the family.
Though phylogenetic signals have been reported for phonological structures, such as phonotactics, their detection
in measures of phonological function is novel. We also find a significant, negative correlation between the FL of
vowel length and of the following consonant—that is, a time-depth historical trade-off dynamic, which we relate to
known allophony in modern PN languages and compensatory sound changes in their past. The findings reveal a
historical dynamic, similar to transphonologization, which we characterize as a flow of contrastiveness between
subsystems of the phonology. Recurring across a language family that spans a whole continent and many millennia of
time depth, our findings provide one of the most compelling examples yet of Sapir’s ‘drift’ hypothesis of
non-accidental parallel development in historically related languages.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Erich R. Round", "Rikker Dockum", "Robin J. Ryder"
]

# parts of the world
groups = ['Pama-Nyungan']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Round2022"  # @xxxx

# type of study
type = ['trait']  # phylogenetic,dating,phylogeography,macroevolutionary,trait
framework = []

# short description of the study, one line.
description = "Modelling the trade-offs in functional load in phonological contrasts in Pama-Nyungan languages"

# data
[data]

    notes = ""
    
    [data.FLV]
    ntaxa = 95
    nchars = 100
    nsites = "?"
    datatype = 'frequency'
    source = ''
    items = ''
    comment = 'vowel length'

    [data.FLC]
    ntaxa = 90
    nchars = 1
    nsites = 1
    datatype = 'frequency'
    source = ''
    items = ''
    comment = 'consonant manner'

    [data.FLP]
    ntaxa = 90
    nchars = 1
    nsites = 1
    datatype = 'frequency'
    source = ''
    items = ''
    comment = 'consonant place'


# published phylogenies
[phylogenies]
    [phylogenies.PN]
    source = '@MacklinCordes2021'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.FLV_K]
    tool = 'picante'
    model = 'K'
    details = ""
    data = "@data.FLV"

    [analysis.FLC_K]
    tool = 'picante'
    model = 'K'
    details = ""
    data = "@data.FLC"

    [analysis.FLP_K]
    tool = 'picante'
    model = 'K'
    details = ""
    data = "@data.FLP"


    [analysis.FLV_vs_FLC]
    tool = 'phytools'
    model = 'correlation'
    details = ""
    data = "@data.FLK;@data.FLC"

    [analysis.FLV_vs_FLP]
    tool = 'phytools'
    model = 'correlation'
    details = ""
    data = "@data.FLK;@data.FLP"

    [analysis.FLC_vs_FLP]
    tool = 'phytools'
    model = 'correlation'
    details = ""
    data = "@data.FLC;@data.FLP"

