title = "(Un)classifying Shabo: phylogenetic methods and results"

doi = ""

abstract = """
Shabo is one of our greatest classification puzzles. The handful of researchers
who have worked on it have tended to place it within the Nilo-Saharan phylum,
though where it should fall within that phylum has been left a mystery. This paper
aims to pursue the Nilo-Saharan hypothesis by reviewing previous evidence and
adding new data from a month spent living among the Shabo in a remote village
in the coffee-growing mountains of southwest Ethiopia.

Beyond documenting a highly endangered language (there are perhaps 400
speakers of Shabo), this paper offers an innovative use of the phylogenetic tools
that biologists have developed for their classification needs. I demonstrate the
potential power of such methods in building classifications and exploring the
increasing amounts of typological data available to us. These tools can be used
heuristically to develop hypotheses: could Shabo be related to Fur, Nubian, or
Ngiti? In this case, no convincing 'phylogenetic signal' emerges. And the
evidence makes a Nilo-Saharan hypothesis especially unlikely. Based on our
current understanding, it is better to call Shabo an isolate like Basque or
Burushaski (see also Hombert & Philippson, this volume).
"""


# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Tyler Schnoebelen"]

# parts of the world
groups = ['Nilo-Saharan']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Schnoebelen2009"

# type of study
type = ['phylogenetic']  # phylogenetic,dating,phylogeography,macroevolutionary,trait,review,tutorial
framework = ['network']

# short description of the study, one line.
description = "An investigation of the sub-grouping of Shabo in Nilo-Saharan"

# data
[data]

    notes = ""
    
    [data.ns]
    ntaxa = 50
    nchars = 47
    nsites = 47
    datatype = 'structural features'
    source = '@WALS;@Schnoebelen2009'
    items = ''
    comment = ''

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.nnet]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = ""
