title = "Evolutionary pathways of complexity in gender systems"

doi = "10.1093/jole/lzae001"

abstract = """
Humans categorize the experience they encounter in various ways, which is mirrored, for
instance, in grammatical gender systems of languages. In such systems, nouns are grouped
based on whether they refer to masculine/feminine beings, (non-)humans, (in)animate
entities, or objects with specific shapes. Languages differ greatly in how many gender
assignment rules are incorporated in gender systems and how many word classes carry gender
marking (gender agreement patterns). It has been suggested that these two dimensions are
positively associated as numerous assignment rules are better sustained by numerous
agreement patterns. We test this claim by analyzing the correlated evolution (Continuous
method in BayesTraits) and making the causal inferences about the relationships
(phylogenetic path analysis) between these 2 dimensions in 482 languages from the global
Grambank database. By applying these methods to linguistic data matched to phylogenetic
trees (a world tree and individual families), we evaluate whether various types of gender
assignment rules (semantic, phonological, and unpredictable) are causally linked to more
gender agreement patterns on the global level and in individual language families. Our
results on the world language tree suggest that semantic rules are weakly positively
correlated with gender agreement and that the development of agreement patterns is
facilitated by different rules in individual families. For example, in Indo-European
languages, more agreement patterns are caused by the presence of phonological and
unpredictable rules, while in Bantu languages, the driving force of agreement patterns is
the variety of semantic rules. Our study shows that the relationships between agreement
and rules are family-specific and yields support to the idea that more distinct rules
and/or rule types might be more robust in languages with more pervasive gender agreement.

"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Olena Shcherbakova", "Marc Allassonnière-Tang"]

# parts of the world
groups = ['global']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Shcherbakova_2024"

# type of study
type = ['trait', 'd-statistic']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['bayesian', 'likelihood'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.grambank]
    ntaxa = 95
    nchars = 4
    nsites = 4
    datatype = 'structural features'
    source = '@Grambank'
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.austronesian]
    source = "@Gray2009"
    comment = ""

    [phylogenies.bantu]
    source = "@Grollemund2015"
    comment = ""
    
    [phylogenies.indoeuropean]
    source = "@Bouckaert2012"
    comment = ""

    [phylogenies.dravidian]
    source = "@Kolipakam2018"
    comment = ""

    [phylogenies.jaeger2018]
    source = "@Jaeger2018"
    comment = ""


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.signal_austronesian_lambda1]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.austronesian"
        
    [analysis.signal_austronesian_lambda2]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.austronesian"
        
    [analysis.signal_austronesian_phylo_d1]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.austronesian"
        
    [analysis.signal_austronesian_phylo_d2]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.austronesian"
        
    [analysis.signal_bantu_lambda1]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.bantu"
        
    [analysis.signal_bantu_lambda2]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.bantu"
        
    [analysis.signal_bantu_phylo_d1]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.bantu"
        
    [analysis.signal_bantu_phylo_d2]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.bantu"
        
    [analysis.signal_indoeuropean_lambda1]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.indoeuropean"
        
    [analysis.signal_indoeuropean_lambda2]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.indoeuropean"
        
    [analysis.signal_indoeuropean_phylo_d1]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.indoeuropean"
        
    [analysis.signal_indoeuropean_phylo_d2]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.indoeuropean"
        
    [analysis.signal_dravidian_lambda1]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.dravidian"
        
    [analysis.signal_dravidian_lambda2]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.dravidian"
        
    [analysis.signal_dravidian_phylo_d1]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.dravidian"
        
    [analysis.signal_dravidian_phylo_d2]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.dravidian"
        
    [analysis.signal_jaeger2018_lambda1]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.jaeger2018"
        
    [analysis.signal_jaeger2018_lambda2]
        tool = 'phytools'
        model = 'lambda'
        details = ""
        data = "@phylogenies.jaeger2018"
        
    [analysis.signal_jaeger2018_phylo_d1]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.jaeger2018"
        
    [analysis.signal_jaeger2018_phylo_d2]
        tool = 'caper'
        model = 'phylo.d'
        details = ""
        data = "@phylogenies.jaeger2018"
        
    [analysis.path_global]
        tool = 'phylopath'
        model = 'x18'
        details = ''
        data = '@phylogenies.jaeger2018'

    [analysis.path_indoeuropean]
        tool = 'phylopath'
        model = 'x18'
        details = ''
        data = '@phylogenies.indoeuropean'

    [analysis.path_bantu]
        tool = 'phylopath'
        model = 'x18'
        details = ''
        data = '@phylogenies.bantu'

    [analysis.cont_indoeuropean]
        tool = 'bayestraits'
        model = 'continuous'
        details = ''
        data = '@phylogenies.indoeuropean'

    [analysis.cont_bantu]
        tool = 'bayestraits'
        model = 'continuous'
        details = ''
        data = '@phylogenies.bantu'

    [analysis.cont_global]
        tool = 'bayestraits'
        model = 'continuous'
        details = ''
        data = '@phylogenies.jaeger2018'

    [analysis.discrete1_dravidian]
        tool = 'bayestraits'
        model = 'discrete'
        details = ''
        data = '@phylogenies.dravidian'

    [analysis.discrete1_austronesian]
        tool = 'bayestraits'
        model = 'discrete'
        details = ''
        data = '@phylogenies.austronesian'

    [analysis.discrete2_dravidian]
        tool = 'bayestraits'
        model = 'discrete'
        details = ''
        data = '@phylogenies.dravidian'

    [analysis.discrete2_austronesian]
        tool = 'bayestraits'
        model = 'discrete'
        details = ''
        data = '@phylogenies.austronesian'
        
    [analysis.independent1_dravidian]
        tool = 'bayestraits'
        model = 'independent'
        details = ''
        data = '@phylogenies.dravidian'

    [analysis.independent1_austronesian]
        tool = 'bayestraits'
        model = 'independent'
        details = ''
        data = '@phylogenies.austronesian'

    [analysis.independent2_dravidian]
        tool = 'bayestraits'
        model = 'independent'
        details = ''
        data = '@phylogenies.dravidian'

    [analysis.independent2_austronesian]
        tool = 'bayestraits'
        model = 'independent'
        details = ''
        data = '@phylogenies.austronesian'

[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []