title = "Coevolution of religious and political authority in Austronesian societies"

doi = "10.1038/s41562-022-01471-y"

abstract = """
Authority, an institutionalized form of social power, is one of the defining features of
the large-scale societies that evolved during the Holocene. Religious and political
authority have deep histories in human societies and are clearly interdependent, but the
nature of their relationship and its evolution over time is contested. We purpose-built an
ethnographic dataset of 97 Austronesian societies and used phylogenetic methods to address
two long-standing questions about the evolution of religious and political authority:
first, how these two institutions have coevolved, and second, whether religious and
political authority have tended to become more or less differentiated. We found evidence
for mutual interdependence between religious and political authority but no evidence for
or against a long-term pattern of differentiation or unification in systems of religious
and political authority. Our results provide insight into how political and religious
authority have worked synergistically over millennia during the evolution of large-scale
societies. """

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Oliver Sheehan", "Joseph Watts", "Russell D. Gray", "Joseph Bulbulia", "Scott Claessens", "Erik J. Ringen", "Quentin D. Atkinson"]

# parts of the world
groups = ['Austronesian']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Sheehan_2022"

# type of study
type = ['regression']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.ethnographic]
    ntaxa = 96
    nchars = 3
    nsites = 3
    datatype = 'ethnographic features'
    source = ''
    items = ''
    comment = 'religious authority, political authority and the structure of religious and political authority'

# published phylogenies
[phylogenies]
    [phylogenies.austronesian]
    source = '@Gray2009'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.regression]
    tool = 'brms'
    model = ''
    details = ""
    data = ""
    times = 100  # 100 random trees

    [analysis.coevolution]
    tool = 'stan'
    model = ''
    details = "Ringen et al."
    data = ""
    times = 100  # 100 random trees

    [analysis.multistate]
    tool = 'bayestraits'
    model = 'multistate'
    details = ""
    data = ""
    times = 5  # 5 models




[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []