title = "Syntactic Phylogenetic Trees"

doi = "10.1007/978-3-319-64813-2_14"

abstract = """
In light of recent controversies surrounding the use of computational methods for the
reconstruction of phylogenetic trees of language families (especially the Indo-European
family), a possible approach based on syntactic information, complementing other
linguistic methods, appeared as a promising possibility, largely developed in recent years
in Longobardi's Parametric Comparison Method. In this paper we identify several serious
problems that arise in the use of syntactic data from the SSWL database for the purpose of
computational phylogenetic reconstruction. We show that the most naive approach fails to
produce reliable linguistic phylogenetic trees. We identify some of the sources of the
observed problems and we discuss how they may be, at least partly, corrected by using
additional information, such as prior subdivision into language families and subfamilies,
and a better use of the information about ancient languages. We also describe how the use
of phylogenetic algebraic geometry can help in estimating to what extent the probability
distribution at the leaves of the phylogenetic tree obtained from the SSWL data can be
considered reliable, by testing it on phylogenetic trees established by other forms of
linguistic analysis. In simple examples, we find that, after restricting to smaller
language subfamilies and considering only those SSWL parameters that are fully mapped for
the whole subfamily, the SSWL data match extremely well reliable phylogenetic trees,
according to the evaluation of phylogenetic invariants. This is a promising sign for the
use of SSWL data for linguistic phylogenetics. We also argue how dependencies and
nontrivial geometry/topology in the space of syntactic parameters would have to be taken
into consideration in phylogenetic reconstructions based on syntactic data. A more
detailed analysis of syntactic phylogenetic trees and their algebro-geometric invariants
will appear elsewhere."""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Kevin Shu", "Sharjeel Aziz", "Vy-Luan Huynh", "David Warrick", "Matilde Marcolli"]

# parts of the world
groups = ['global']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Shu_2018"

# type of study
type = ['phylogenetic']
framework = ['distance', 'network']
# short description of the study, one line.
description = ""

# data
[data]

    notes = "115 parameters over 253 world languages"
    
    [data.sswl]
    ntaxa = 253
    nchars = 115
    nsites = 1
    datatype = 'syntactical features'
    source = '@SSWL'
    items = ''
    comment = 'converted to distance'

# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = 'phylip'
    model = '?'
    details = ""
    data = ""

    [analysis.network]
    tool = 'splitstree'
    model = 'neighbornet'
    details = ""
    data = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []