title = "Testing Inferences about Language Contact on Morphosyntax: A Typological Case Study on Alorese-Adang Contact"

doi = "10.1111/1467-968X.12284"

abstract = """
When linguists make inferences about language contact, control data is required for
reliable analysis. Historical data or reconstructions are typically used for that purpose.
However, historical data is globally mostly unavailable, and reconstructions are laborious
if comparing outcomes of language contact in a typological way. We assess a recent
typological proposal (Di Garbo & Napoleão de Souza 2023) that argues that using a single
language, called Benchmark language, can serve as a viable control for making inferences
about contact. To evaluate this approach, we use as a case study a documented contact
situation in Eastern Indonesia between the Austronesian language Alorese and the Papuan
language Adang. We sample languages related to Alorese and use computational phylogenetic
methods for ancestral reconstruction to analyse if using a single Benchmark produces
deviating inferences about contact compared to using Bayesian ancestral reconstructions.
Additionally, we test for isolation by distance effects by analysing if the probability of
contact effects correlates with increasing geographic distance from the contact region.
The results suggest that no isolation by distance effects exist in the data and that none
of the single Benchmarks significantly deviate from the ancestral reconstructions.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Kaius Sinnemäki", "Noora Ahola"]

# parts of the world
groups = ['Austronesian']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Sinnem_ki_2023"

# type of study
type = ['asr']
framework = ['bayesian']
description = ""

# data
[data]

    notes = ""
    
    [data.alorese]
    ntaxa = 22
    nchars = 12
    nsites = 12
    datatype = 'structural features'
    source = ''
    items = ''
    comment = ''


# published phylogenies
[phylogenies]
    [phylogenies.glottolog]
    source = '@Glottolog47'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.asr]
    tool = 'phytools'
    model = 'ancThresh'
    details = ""
    data = "@data.phylogenies;@data.alorese"


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []