title = "Environmental factors affect the evolution of linguistic subgroups in Borneo"

doi = "10.17613/v31m-0w40"

abstract = """
This study investigates the relatedness and history of the Austronesian languages
of Borneo, which is the third largest island in the world and home to
significant linguistic diversity. We apply Bayesian phylogenetic dating methods
to lexical cognate data based on four historical calibration points to
infer a dated phylogeny of 87 languages. The inferred tree topology agrees
with the mid and lower-level subgrouping proposals based on the classical
comparative method, but suggests a different higher-level organization. The
root age of the dated tree is shallower than the archaeological estimates but
agrees with a hypothesis of a past linguistic leveling event. The inferred
homelands of the major linguistic subgroups from a Bayesian phylogeographic
analysis agree with the homeland proposals from archaeology and
linguistics. The inferred homelands for four of the eight subgroups support
the riverine homeland hypothesis whereby the major linguistic subgroups
developed initially in communities situated along Borneo's major rivers.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Alexander D. Smith", "Taraka Rama"]

# parts of the world
groups = ['Austronesian']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Smith_2021"

# type of study
type = ['phylogenetic', 'phylogeography', 'delta', 'qresidual']
framework = ['bayesian', 'network']

# data
[data]

    notes = ""
    
    [data.borneo]
    ntaxa = 87
    nchars = 229
    nsites = 2966
    datatype = 'lexical cognates (autodetected)'
    source = ''
    items = ''
    comment = ''


# date calibrations
[calibrations]

    notes = ""

    [calibration.ukit_buket]
    taxa = ["buka1263"]
    age = "uniform(250, 350)"
    units = "ybp" # ybp
    description = ""

    [calibration.punan]
    taxa = ["puna1280"]
    age = "uniform(500, 600)"
    units = "ybp" # ybp
    description = ""

    [calibration.tunjung_benuaq]
    taxa = ["grea1283"]
    age = "uniform(600, 5000)"
    units = "ybp" # ybp
    description = ""

    [calibration.maanyan_dusun]
    taxa = ["maan1238", "dusu1267"]
    age = "uniform(1300, 1400)"
    units = "ybp" # ybp
    description = ""

    [calibration.root]
    taxa = []
    age = "uniform(0, 10000)"
    units = "ybp" # ybp
    description = ""


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.mrbayes_unconstrained]
    tool = 'mrbayes'
    model = 'ctmc+gamma4+igr+fbd'
    details = ""
    data = ""

    [analysis.mrbayes_constrained]
    tool = 'mrbayes'
    model = 'ctmc+gamma4+igr+fbd'
    details = ""
    data = "topology constrained"

    [analysis.delta]
    tool = 'splitstree'
    model = 'delta'
    details = ""
    data = ""

    [analysis.qresidual]
    tool = 'splitstree'
    model = 'qresidual'
    details = ""
    data = ""

    [analysis.btv]
    tool = 'bayestraits'
    model = 'btv'
    details = ""
    data = ""

    [analysis.btf]
    tool = 'bayestraits'
    model = 'btf'
    details = ""
    data = ""

    [analysis.btf_fossil]
    tool = 'bayestraits'
    model = 'btf_fossil'
    details = ""
    data = ""
    


[inferredages]
    
    notes = ""

    [inferredage.mrbayes_unconstrained]
    taxa = ["nort3253", "land1261", "mala1536", "grea1283"]  # Borneo
    age = "hpd(2692, 2085, 3421)"
    units = "ybp"
    notes = ""

    [inferredage.mrbayes_constrained]
    taxa = ["nort3253", "land1261", "mala1536", "grea1283"]  # Borneo
    age = "hpd(2992, 2318, 3900)"
    units = "ybp"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []