title = "Food storage facilitates professional religious specialization in hunter–gatherer societies"

doi = "10.1017/ehs.2022.17"

abstract = """
Professional religious specialists centralised religious authority in early human societies and represented
some of the earliest instances of formalised social leadership. These individuals played a central role in
the emergence of organised religion and transitions to more stratified human societies. Evolutionary
theories highlight a range of environmental, economic and social factors that are potentially causally
related to the emergence of professional religious specialists in human history. There remains little con-
sensus over the relative importance of these factors and whether professional religious specialists were the
outcome or driver of increased socio-cultural complexity. We built a global dataset of hunter–gatherer
societies and developed a novel method of exploratory phylogenetic path analysis. This enabled us to
systematically identify the factors associated with the emergence of professional religious specialists and
infer the directionality of causal dependencies. We find that environmental predictability, environmental
richness, pathogen load, social leadership and food storage systems are all correlated with professional
religious specialists. However, only food storage is directly related to the emergence of professional
religious specialists. Our findings are most consistent with the claim that the early stages of organised
religion were the outcome rather than driver of increased socio-economic complexity.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Joseph Watts", "Elise M. Hamerslag", "Cassie Sprules", "John H. Shaver", "Robin I. M. Dunbar"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Watts_2022"

# type of study
type = ['d-statistic']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = [] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.HGRD]
    ntaxa = 84
    nchars = "?"
    nsites = "?"
    datatype = 'ethnographic features'
    source = '@HGRD'
    items = ''
    comment = ''

    [data.dplace]
    ntaxa = 84
    nchars = "?"
    nsites = "?"
    datatype = 'ethnographic features'
    source = '@DPLACE'
    items = ''
    comment = ''
    
# published phylogenies
[phylogenies]
    [phylogenies.glottolog]
    source = '@Glottolog43'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.dstatistic]
    tool = 'caper'
    model = 'phylo.d'
    details = ""
    data = ""

    [analysis.phylopath]
    tool = 'phylopath'
    model = 'phylopath'
    details = ""
    data = ""
    times = 277667 


[inferredages]
    
    notes = ""
    
    [inferredage.label]
    taxa = []
    age = "hpd(median, lower, upper)"
    units = "bp"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []