
title = "Dated phylogeny suggests early Neolithic origin of Sino-Tibetan languages"

doi = "10.1038/s41598-020-77404-4"

abstract = """
An accurate reconstruction of Sino‑Tibetan language evolution would greatly advance our understanding of East Asian population history. Two recent phylogenetic studies attempted to do so but several of their conclusions are different from each other. Here we reconstruct the phylogeny of the Sino‑Tibetan language family, using Bayesian computational methods applied to a larger and linguistically more diverse sample. Our results confirm previous work in finding that the ancestral SinoTibetans first split into Sinitic and Tibeto‑Burman clades, and support the existence of key internal relationships. But we find that the initial divergence of this group occurred earlier than previously suggested, at approximately 8000 years before the present, coinciding with the onset of millet‑based agriculture and significant environmental changes in theYellow River region. Our findings illustrate that key aspects of phylogenetic history can be replicated in this complex language family, and calls for a more nuanced understanding of the first Sino‑Tibetan speakers in relation to the 'early farming dispersal' theory of language evolution.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = [
    "Hanzhi Zhang",
    "Ting Ji",
    "Mark Pagel",
    "Ruth Mace"
]

# parts of the world
groups = ["Sino-Tibetan"]  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Zhang2020"

# type of study
type = ["phylogenetic", "dating"]
framework = ['bayesian']

# short label of taxa "37 languages from.."
description = "131 Sino-Tibetan languages"

# data
[data]
    [data.lexicon]
    ntaxa = 131
    nchars = 110
    nsites = 1726
    datatype = 'lexical cognates'
    source = ''
    items = ''
    comment = ''
    

[calibration]
    notes = """
    We incorporated six time-calibrations on the tree (Table S1). Extinction
    timings of Old Chinese, Padam, and Shaiyang were calibrated with last-seen
    dates identified by linguists66,72; three internal nodes were calibrated
    based on historical records of the earliest observation of distinct
    descendant groups as the latest date of their most recent common ancestor
    """

    [calibration.oldc1244]
    taxa = ["oldc1244"]
    age = "uniform(2300, 2800)"
    units = "y2000" # ybp
    description = "300 ~ 800 B.C."

    [calibration.padam]
    taxa = ["pada1257"]
    age = "120"
    units = "y2000" # ybp
    description = "extinction of Padam ~1900AD"

    [calibration.Shaiyang]
    taxa = ["misi1242"]
    age = "120"
    units = "y2000" # ybp
    description = "extinction of Shaiyang ~1900AD"

    [calibration.loloquangic]
    taxa = ["burm1265"]
    age = ">1602"
    units = "y2000" # ybp
    description = "Lolo-Qiangic common ancestor before 418 AD"

    [calibration.pumi]
    taxa = ["pumi1242"]
    age = ">157"
    units = "y2000" # ybp
    description = "Pumi common ancestor before 1863 AD"

    [calibration.naxi]
    taxa = ["naxi1245"]
    age = ">297"
    units = "y2000" # ybp
    description = "Pumi common ancestor before 1724 AD"



# analysis information
[analysis]
    [analysis.tree1]
    tool = 'beast2'
    model = 'ctmc+strict+fbd'
    details = ""

    [analysis.tree2]
    tool = 'beast2'
    model = 'ctmc+relaxed+fbd'
    details = ""

    [analysis.tree3]
    tool = 'beast2'
    model = 'ctmc+gamma4+strict+fbd'
    details = ""
    
    [analysis.tree4]
    tool = 'beast2'
    model = 'ctmc+gamma4+relaxed+fbd'
    details = ""

    [analysis.tree5]
    tool = 'beast2'
    model = 'covarion+strict+fbd'
    details = ""

    [analysis.tree6]
    tool = 'beast2'
    model = 'covarion+relaxed+fbd'
    details = "best fitting model"
    best = "true"

[inferredages]
    
    notes = ""
    
    [inferredage.root]
    taxa = ['sino1245']
    age = "hpd(7983, 4778, 11285)"
    units = "y2000"
    details = "best fitting model"
    best = "true"

    [inferredage.Lolo-Qiangic]
    taxa = ["lolo1265"]
    age = "hpd(3200, 1900, 4700)"
    units = "y2000"
    details = "best fitting model"
    best = "true"


    [inferredage.Tibetan-Qiangic]
    taxa = ["burm1265"]
    age = "hpd(4100, 2500, 6100)"
    units = "y2000"
    details = "best fitting model"
    best = "true"

    [inferredage.Kiranti]
    taxa = ["kira1253"]
    age = "hpd(2100, 1200, 3200)"
    units = "y2000"
    details = "best fitting model"
    best = "true"

    [inferredage.Tani-Idu]
    taxa = ["tani1259", "idum1241"]
    age = "hpd(5000, 2500, 7100)"
    units = "y2000"
    details = "best fitting model"
    best = "true"

    [inferredage.Sal]
    taxa = ["brah1260"]
    age = "hpd(3900, 2100, 5800)"
    units = "y2000"
    details = "best fitting model"
    best = "true"

    [inferredage.Kuki-Karbi]
    taxa = ["kuki1246", "karb1240"]
    age = "hpd(4500, 2500, 6600)"
    units = "y2000"
    details = "best fitting model"
    best = "true"


    [inferredage.Karenic]
    taxa = ["kare1337"]
    age = "hpd(1300, 700, 1900)"
    units = "y2000"
    details = "best fitting model"
    best = "true"


    [inferredage.Naga]
    taxa = ["naga1409"]
    age = "hpd(2600, 1600, 4000)"
    units = "y2000"
    details = "best fitting model"
    best = "true"


    [inferredage.Sinitic]
    taxa = ["sini1245"]
    age = '2600'
    units = "y2000"
    details = "best fitting model"
    best = "true"




[links]
phlorest = { title = "Phlorest Dataset", link = "https://github.com/phlorest/zhang_et_al2020" }
cldf = { title = "CLDF Dataset", link = "" }
links = []
